wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.2
    framework: huggingface
    huggingface_version: 4.28.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1683990777.516206
    t:
      1:
      - 1
      - 5
      - 11
      - 33
      - 49
      - 51
      - 53
      - 55
      3:
      - 23
      4: 3.10.8
      5: 0.15.2
      6: 4.28.1
      8:
      - 1
      - 3
      - 5
