Improve sentences
----------------------------

In this notebook we want to improve the corpora of new sentences and the final corpora which is the concatenation of the original corpora and the new one (we got the two in the following notebook [new_sentences](extract_new_sentences.ipynb)). 

For the improvement we want to make the following modifications that we found to be necessary after fine-tuning the `t5` model on the new sentences:

- Remove the definitions: We had already extract the new sentences without the definitions we will only need to load the "true sentences".
- Replace exclamation marks (!) at the end of the phrases by period marks (.): This will help the transformers to identify the end of a sentence. Not that we will do this for both of the new sentences and the last version corpora (v4). We cannot know if it is the right thing to do in order to obtain better performance that's why we will create a function and add it when making hyper-parameter search and reduce the search space if necessary.
- Remove sentences with less than 3 tokens in one of the French of Wolof version. This will reduce the number of sentences but can provide better agreement with the right way to write sentences.

The above modifications on the version 4 of the corpora and the diagne's sentences will be necessary to create the version 5 of the corpora. The additional version of the diagne's sentences and 6 of the corpora will understand additionally sentences got from `omniglot`. We will not select the sentences by length for the new versions.

All the modifications can be done with the `pandas` library.

In [1]:
import re
import pandas as pd
from tokenizers.pre_tokenizers import Whitespace
from wolof_translate.utils.database_manager import TranslationMongoDBManager

### Remove the definitions

Let us load the two corpora.

In [2]:
corpora_v4 = pd.read_csv('data/extractions/new_data/corpora_v4.csv')

diagne_sentences = pd.read_csv('data/extractions/new_data/sentences.csv')

In [3]:
corpora_v4.to_csv('verification.csv', index=False)

In [4]:
corpora_v4.shape[0], diagne_sentences.shape[0]

(2500, 1615)

### Add periods to the end of the sentences

We have three possibilities:

- We can replace the exclamations by period marks (option 2)
- ... add period mark at each end of sentences (option 3)
- ... do the two previous modification at same time (option 4)

The following function will be added inside the `TransformerSequences` class when recuperating the sentences before the training.

In [5]:
%%writefile wolof-translate/wolof_translate/utils/improvements/end_marks.py

import pandas as pd
from typing import *

def add_end_mark(sentences: Union[list, str], end_mark: str = ".", end_mark_to_remove: Union[str, None] = None, 
                 replace: bool = False, poss_end_marks: list = ['!', '?', '.', '...']):
    
    if isinstance(sentences, str): sentences = [sentences]
    
    if replace and end_mark_to_remove is None:
        
        raise ValueError("You must provide a end mark to remove if you want to make replacement !")
    
    new_sentences = []
    
    # if replace is chosen we will replace the end to remove by the end mark if not only add end mark to each sentence and remove the end mark to remove
    for sentence in sentences:
        
        if replace:
            
            if sentence[-1] == end_mark_to_remove:
                
                sentence = sentence[:-1].strip() + end_mark
            
        else:
            
            if not end_mark_to_remove is None and sentence[-1] == end_mark_to_remove:
                
                sentence = sentence[:-1]
            
            if not sentence[-1] in poss_end_marks: 
                
                sentence = sentence.strip() + end_mark
        
        new_sentences.append(sentence)
    
    return new_sentences
    

Overwriting wolof-translate/wolof_translate/utils/improvements/end_marks.py


Let us try the different type of end mark adding with the above function.

In [6]:
%run wolof-translate/wolof_translate/utils/improvements/end_marks.py

In [7]:
# recuperate some sentences from the diagne's sentences
sample = diagne_sentences.sample(30)

In [8]:
sample

french  \
1010                Et ne viens surtout pas à l'école !   
104                             Ce mouton-là en entier.   
284                              C'est quand tu es venu   
1531    Si tu veux, retourne au centre de Saint-Louis !   
204                                   C'est des femmes.   
1564  Je veux que tu viennes le matin à cinq heures ...   
317                                             Vas-y !   
1560       Ce matin ou ce soir c'est moi qui suis ici !   
719                                     C'est celui-là.   
54                                J'ai aperçu un homme.   
985                          Là où il y a de la lumière   
20                                    J'ai vu la femme.   
124                        Aucun mouton ne s'est égaré.   
470             Les gens n'eussent pas été des maîtres.   
1336                       J'ai vu des vaches d'Europe.   
1482  Les enfants ont cherché à l'intérieur, à l'ext...   
1326                                  Vous fûtes Laobé.   
1440         L'homme a tenu aux enfants de bons propos.   
872                         Il est venu à cause de toi.   
45                     Je connaissais cet individu-là !   
4                             Homme n'est pas mauvais !   
697                          D'ailleurs, je m'en vais !   
1265                       J'ai aperçu une jeune fille.   
1340   Il n'est de Ardo du Dieri que tu ne connaisses !   
731                                   Que pleure-t-il ?   
1284                                Honore tout homme !   
663                              Voilà ce qu'il en est.   
1495        L'enfant dit d'entrer pour qu'il vous voie.   
649                                              Quoi ?   
248                        C'est cette ville de Sérère.   

                                               wolof  
1010                        Te bul ñëw jaŋgu ba de !  
104                                Xar moomule mépp.  
284                                  Bi ŋga ñëwée la  
1531                  Dellu, soo bëggée, biir Ndar !  
204                                     Jigéen lanu.  
1564   Bëgg naa ci juróomi waxtu, ci subë, ŋga ñëw !  
317                                         Dem fa !  
1560        Maa fiy nekk tày ci ŋgoon, tày ci suba !  
719                                         Kile la.  
54                                  Séen naa aw nit.  
985                                 Ci biir fiy leer  
20                                Gis naa jigéen ju.  
124                                 Menn xar réerul.  
470                      Nit ñi doonkoonuñu ay kaaŋ.  
1336                             Gis naa nagu Tugël.  
1482  Xale yi set nañu ci biir, ci biti gisuñu dara.  
1326                               Laobe ŋgeen woon.  
1440            Góor gi wax na xale yi wax ju rafet.  
872                                Dikk na ndax yaw.  
45                           Xamoon naa waa joojee !  
4                                        Nit bonul !  
697                            Te sax, ma ŋgii dem !  
1265                               Séen naa as ndaw.  
1340               Amul benn ardow Jéeri boo xamul !  
731                                    Lu muy jooy ?  
1284                              Teralal bépp nit !  
663                                        Loolu la.  
1495              Xale bi ne ŋgeen dugg mu gis leen.  
649                                        Lii lan ?  
248                            Gii dëkku Séeréer la.

We need to add the modification on each version of the sentences.

- Replace exclamations by end marks.

In [9]:
french_sents = sample['french'].to_list()

wolof_sents = sample['wolof'].to_list()

french_sents = add_end_mark(french_sents, end_mark_to_remove='!', replace=True)

wolof_sents = add_end_mark(wolof_sents, end_mark_to_remove='!', replace=True)

pd.DataFrame({'french': french_sents, 'wolof': wolof_sents})


french  \
0                  Et ne viens surtout pas à l'école.   
1                             Ce mouton-là en entier.   
2                              C'est quand tu es venu   
3      Si tu veux, retourne au centre de Saint-Louis.   
4                                   C'est des femmes.   
5   Je veux que tu viennes le matin à cinq heures ...   
6                                              Vas-y.   
7         Ce matin ou ce soir c'est moi qui suis ici.   
8                                     C'est celui-là.   
9                               J'ai aperçu un homme.   
10                         Là où il y a de la lumière   
11                                  J'ai vu la femme.   
12                       Aucun mouton ne s'est égaré.   
13            Les gens n'eussent pas été des maîtres.   
14                       J'ai vu des vaches d'Europe.   
15  Les enfants ont cherché à l'intérieur, à l'ext...   
16                                  Vous fûtes Laobé.   
17         L'homme a tenu aux enfants de bons propos.   
18                        Il est venu à cause de toi.   
19                    Je connaissais cet individu-là.   
20                           Homme n'est pas mauvais.   
21                          D'ailleurs, je m'en vais.   
22                       J'ai aperçu une jeune fille.   
23    Il n'est de Ardo du Dieri que tu ne connaisses.   
24                                  Que pleure-t-il ?   
25                                 Honore tout homme.   
26                             Voilà ce qu'il en est.   
27        L'enfant dit d'entrer pour qu'il vous voie.   
28                                             Quoi ?   
29                       C'est cette ville de Sérère.   

                                             wolof  
0                          Te bul ñëw jaŋgu ba de.  
1                                Xar moomule mépp.  
2                                  Bi ŋga ñëwée la  
3                    Dellu, soo bëggée, biir Ndar.  
4                                     Jigéen lanu.  
5     Bëgg naa ci juróomi waxtu, ci subë, ŋga ñëw.  
6                                          Dem fa.  
7          Maa fiy nekk tày ci ŋgoon, tày ci suba.  
8                                         Kile la.  
9                                 Séen naa aw nit.  
10                                Ci biir fiy leer  
11                              Gis naa jigéen ju.  
12                                Menn xar réerul.  
13                     Nit ñi doonkoonuñu ay kaaŋ.  
14                             Gis naa nagu Tugël.  
15  Xale yi set nañu ci biir, ci biti gisuñu dara.  
16                               Laobe ŋgeen woon.  
17            Góor gi wax na xale yi wax ju rafet.  
18                               Dikk na ndax yaw.  
19                          Xamoon naa waa joojee.  
20                                      Nit bonul.  
21                            Te sax, ma ŋgii dem.  
22                               Séen naa as ndaw.  
23                Amul benn ardow Jéeri boo xamul.  
24                                   Lu muy jooy ?  
25                               Teralal bépp nit.  
26                                       Loolu la.  
27              Xale bi ne ŋgeen dugg mu gis leen.  
28                                       Lii lan ?  
29                           Gii dëkku Séeréer la.

- Add end marks at each sentence without replacing or removing

In [10]:
french_sents = sample['french'].to_list()

wolof_sents = sample['wolof'].to_list()

french_sents = add_end_mark(french_sents)

wolof_sents = add_end_mark(wolof_sents)

pd.DataFrame({'french': french_sents, 'wolof': wolof_sents})


french  \
0                 Et ne viens surtout pas à l'école !   
1                             Ce mouton-là en entier.   
2                             C'est quand tu es venu.   
3     Si tu veux, retourne au centre de Saint-Louis !   
4                                   C'est des femmes.   
5   Je veux que tu viennes le matin à cinq heures ...   
6                                             Vas-y !   
7        Ce matin ou ce soir c'est moi qui suis ici !   
8                                     C'est celui-là.   
9                               J'ai aperçu un homme.   
10                        Là où il y a de la lumière.   
11                                  J'ai vu la femme.   
12                       Aucun mouton ne s'est égaré.   
13            Les gens n'eussent pas été des maîtres.   
14                       J'ai vu des vaches d'Europe.   
15  Les enfants ont cherché à l'intérieur, à l'ext...   
16                                  Vous fûtes Laobé.   
17         L'homme a tenu aux enfants de bons propos.   
18                        Il est venu à cause de toi.   
19                   Je connaissais cet individu-là !   
20                          Homme n'est pas mauvais !   
21                         D'ailleurs, je m'en vais !   
22                       J'ai aperçu une jeune fille.   
23   Il n'est de Ardo du Dieri que tu ne connaisses !   
24                                  Que pleure-t-il ?   
25                                Honore tout homme !   
26                             Voilà ce qu'il en est.   
27        L'enfant dit d'entrer pour qu'il vous voie.   
28                                             Quoi ?   
29                       C'est cette ville de Sérère.   

                                             wolof  
0                         Te bul ñëw jaŋgu ba de !  
1                                Xar moomule mépp.  
2                                 Bi ŋga ñëwée la.  
3                   Dellu, soo bëggée, biir Ndar !  
4                                     Jigéen lanu.  
5    Bëgg naa ci juróomi waxtu, ci subë, ŋga ñëw !  
6                                         Dem fa !  
7         Maa fiy nekk tày ci ŋgoon, tày ci suba !  
8                                         Kile la.  
9                                 Séen naa aw nit.  
10                               Ci biir fiy leer.  
11                              Gis naa jigéen ju.  
12                                Menn xar réerul.  
13                     Nit ñi doonkoonuñu ay kaaŋ.  
14                             Gis naa nagu Tugël.  
15  Xale yi set nañu ci biir, ci biti gisuñu dara.  
16                               Laobe ŋgeen woon.  
17            Góor gi wax na xale yi wax ju rafet.  
18                               Dikk na ndax yaw.  
19                         Xamoon naa waa joojee !  
20                                     Nit bonul !  
21                           Te sax, ma ŋgii dem !  
22                               Séen naa as ndaw.  
23               Amul benn ardow Jéeri boo xamul !  
24                                   Lu muy jooy ?  
25                              Teralal bépp nit !  
26                                       Loolu la.  
27              Xale bi ne ŋgeen dugg mu gis leen.  
28                                       Lii lan ?  
29                           Gii dëkku Séeréer la.

- Remove exclamation marks and add period marks

In [11]:
french_sents = sample['french'].to_list()

wolof_sents = sample['wolof'].to_list()

french_sents = add_end_mark(french_sents, end_mark_to_remove='!')

wolof_sents = add_end_mark(wolof_sents, end_mark_to_remove='!')

pd.DataFrame({'french': french_sents, 'wolof': wolof_sents})


french  \
0                  Et ne viens surtout pas à l'école.   
1                             Ce mouton-là en entier.   
2                             C'est quand tu es venu.   
3      Si tu veux, retourne au centre de Saint-Louis.   
4                                   C'est des femmes.   
5   Je veux que tu viennes le matin à cinq heures ...   
6                                              Vas-y.   
7         Ce matin ou ce soir c'est moi qui suis ici.   
8                                     C'est celui-là.   
9                               J'ai aperçu un homme.   
10                        Là où il y a de la lumière.   
11                                  J'ai vu la femme.   
12                       Aucun mouton ne s'est égaré.   
13            Les gens n'eussent pas été des maîtres.   
14                       J'ai vu des vaches d'Europe.   
15  Les enfants ont cherché à l'intérieur, à l'ext...   
16                                  Vous fûtes Laobé.   
17         L'homme a tenu aux enfants de bons propos.   
18                        Il est venu à cause de toi.   
19                    Je connaissais cet individu-là.   
20                           Homme n'est pas mauvais.   
21                          D'ailleurs, je m'en vais.   
22                       J'ai aperçu une jeune fille.   
23    Il n'est de Ardo du Dieri que tu ne connaisses.   
24                                  Que pleure-t-il ?   
25                                 Honore tout homme.   
26                             Voilà ce qu'il en est.   
27        L'enfant dit d'entrer pour qu'il vous voie.   
28                                             Quoi ?   
29                       C'est cette ville de Sérère.   

                                             wolof  
0                          Te bul ñëw jaŋgu ba de.  
1                                Xar moomule mépp.  
2                                 Bi ŋga ñëwée la.  
3                    Dellu, soo bëggée, biir Ndar.  
4                                     Jigéen lanu.  
5     Bëgg naa ci juróomi waxtu, ci subë, ŋga ñëw.  
6                                          Dem fa.  
7          Maa fiy nekk tày ci ŋgoon, tày ci suba.  
8                                         Kile la.  
9                                 Séen naa aw nit.  
10                               Ci biir fiy leer.  
11                              Gis naa jigéen ju.  
12                                Menn xar réerul.  
13                     Nit ñi doonkoonuñu ay kaaŋ.  
14                             Gis naa nagu Tugël.  
15  Xale yi set nañu ci biir, ci biti gisuñu dara.  
16                               Laobe ŋgeen woon.  
17            Góor gi wax na xale yi wax ju rafet.  
18                               Dikk na ndax yaw.  
19                          Xamoon naa waa joojee.  
20                                      Nit bonul.  
21                            Te sax, ma ŋgii dem.  
22                               Séen naa as ndaw.  
23                Amul benn ardow Jéeri boo xamul.  
24                                   Lu muy jooy ?  
25                               Teralal bépp nit.  
26                                       Loolu la.  
27              Xale bi ne ŋgeen dugg mu gis leen.  
28                                       Lii lan ?  
29                           Gii dëkku Séeréer la.

### Remove sentences with less than 3 tokens

Only the words interest us and we want to separate them by space or marks. Notice also that we want verify for each version and if one it is not accepted then the another one also.

In [12]:
def select_by_length(sentences: pd.DataFrame, min_len: int = 4):
    
    new_sentences = {'french': [], 'wolof': []}
    
    for i in list(sentences.index):
        
        sent1 = sentences.loc[i, 'french']
        
        sent2 = sentences.loc[i, 'wolof']
        
        tokens1 = re.findall('\w+', sent1)
        
        tokens2 = re.findall('\w+', sent2)
        
        take = True
        
        if len(tokens1) < min_len or len(tokens2) < min_len:
            
            take = False
        
        if take:
            
            new_sentences['french'].append(sent1)
            
            new_sentences['wolof'].append(sent2)
            
    return pd.DataFrame(new_sentences)

Let us make an example with the sample that we got earlier.

In [13]:
sample = select_by_length(sample, min_len=3)


In [14]:
sample

french  \
0                 Et ne viens surtout pas à l'école !   
1                             Ce mouton-là en entier.   
2                              C'est quand tu es venu   
3     Si tu veux, retourne au centre de Saint-Louis !   
4   Je veux que tu viennes le matin à cinq heures ...   
5        Ce matin ou ce soir c'est moi qui suis ici !   
6                               J'ai aperçu un homme.   
7                          Là où il y a de la lumière   
8                                   J'ai vu la femme.   
9                        Aucun mouton ne s'est égaré.   
10            Les gens n'eussent pas été des maîtres.   
11                       J'ai vu des vaches d'Europe.   
12  Les enfants ont cherché à l'intérieur, à l'ext...   
13                                  Vous fûtes Laobé.   
14         L'homme a tenu aux enfants de bons propos.   
15                        Il est venu à cause de toi.   
16                   Je connaissais cet individu-là !   
17                         D'ailleurs, je m'en vais !   
18                       J'ai aperçu une jeune fille.   
19   Il n'est de Ardo du Dieri que tu ne connaisses !   
20                                  Que pleure-t-il ?   
21                                Honore tout homme !   
22        L'enfant dit d'entrer pour qu'il vous voie.   
23                       C'est cette ville de Sérère.   

                                             wolof  
0                         Te bul ñëw jaŋgu ba de !  
1                                Xar moomule mépp.  
2                                  Bi ŋga ñëwée la  
3                   Dellu, soo bëggée, biir Ndar !  
4    Bëgg naa ci juróomi waxtu, ci subë, ŋga ñëw !  
5         Maa fiy nekk tày ci ŋgoon, tày ci suba !  
6                                 Séen naa aw nit.  
7                                 Ci biir fiy leer  
8                               Gis naa jigéen ju.  
9                                 Menn xar réerul.  
10                     Nit ñi doonkoonuñu ay kaaŋ.  
11                             Gis naa nagu Tugël.  
12  Xale yi set nañu ci biir, ci biti gisuñu dara.  
13                               Laobe ŋgeen woon.  
14            Góor gi wax na xale yi wax ju rafet.  
15                               Dikk na ndax yaw.  
16                         Xamoon naa waa joojee !  
17                           Te sax, ma ŋgii dem !  
18                               Séen naa as ndaw.  
19               Amul benn ardow Jéeri boo xamul !  
20                                   Lu muy jooy ?  
21                              Teralal bépp nit !  
22              Xale bi ne ŋgeen dugg mu gis leen.  
23                           Gii dëkku Séeréer la.

It only kept 26 samples. Let us make the same for all the sentences.

In [15]:
diagne_sentences = select_by_length(diagne_sentences, min_len=3)

corpora_v4 = select_by_length(corpora_v4, min_len=3)

Let us verify how many sentences we have kept.

In [16]:
# for diagne's sentences
diagne_sentences.shape[0]

1329

In [17]:
# in corpora v4
corpora_v4.shape[0]

2213

We removed $651$ sentences from the corpora v4 and $645$ sentences from the diagne's sentences.

Let us save the results to make again hyperparameter search with them.

In [18]:
# save the new version of the diagne's sentences in red_sentences.csv
diagne_sentences.to_csv('data/extractions/new_data/red_sentences.csv', index = False)

# save the new version of the corpora
corpora_v4.to_csv('data/extractions/new_data/corpora_v5.csv', index = False)

### Recuperate additional sentences 

In [19]:
corpora_v4 = pd.read_csv('data/extractions/new_data/corpora_v4.csv')

diagne_sentences = pd.read_csv('data/extractions/new_data/sentences.csv')

Let us recuperate additional sentences to augment the corpora.

- First file:

In [20]:
path = 'data/additional_documents/omniglot/sentences_french_wolof.txt'

with open(path, 'r', encoding='utf-8') as f:
    
    # recuperate lines
    omn_1 = f.readlines()
    
# recuperate sentences
omn_1_ = {
    'french': [],
    'wolof': []
}

for omn in omn_1:
    
    omn = omn.split('\t')
    
    sentences = [s.strip() for s in omn if s.strip() != '']
    
    omn_1_['french'].append(sentences[0])
    
    omn_1_['wolof'].append(sentences[1])

In [21]:
pd.options.display.max_rows = 74
omn_1_ = pd.DataFrame(omn_1_).head(74)

# print the first sentences from omniglot
omn_1_.head(74)

french  \
0                                    Bienvenue   
1                                        Salut   
2                                        Salut   
3                                        Salut   
4                             Comment vas-tu ?   
5                              Es-tu en paix ?   
6                             Comment vas-tu ?   
7                     Paix seulement, et toi ?   
8      Je suis seulement toi, comment vas-tu ?   
9      Ça fait longtemps que je ne t'ai pas vu   
10                     Comment t'appelles-tu ?   
11                     Comment t'appelles-tu ?   
12                     Comment t'appelles-tu ?   
13                             Mon nom est ...   
14                             Mon nom est ...   
15                           Je m'appelles ...   
16                             D'où viens-tu ?   
17                           D'où venez-vous ?   
18                             Je viens de ...   
19                             Je viens de ...   
20                    Plaisir de te rencontrer   
21                    Content de te rencontrer   
22            Je suis content de te rencontrer   
23                                   Bon matin   
24                            Bonne après-midi   
25                                Bonne soirée   
26                                   Au revoir   
27                                   Au revoir   
28                              Bonne chance !   
29                               Bonne santé !   
30                      Aies une bonne journée   
31                                  Bon voyage   
32                              Comprends-tu ?   
33                                Je comprends   
34                         Je ne comprends pas   
35                        Je ne le connais pas   
36                           Je ne le sais pas   
37      S'il te plaît, parles plus lentement !   
38                     Répètes s'il te plaît !   
39                       Ecris s'il te plaît !   
40                         Parles-tu anglais ?   
41                           Parles-tu Wolof ?   
42                                 Oui, un peu   
43            Comment dis t-on ceci en Wolof ?   
44                                Excuse-moi !   
45                          Combien ça coute ?   
46                                Pardonne-moi   
47                                  Si tu veux   
48                                       Merci   
49                                       Viens   
50                               Venez en paix   
51                     Où sont les toilettes ?   
52  Ce garçon peut te payer pour n'import quoi   
53             Cette jeune fille va tout payer   
54             Accepte-tu de danser avec moi ?   
55             Accepte-tu de danser avec moi ?   
56                               Tu me manques   
57                                  Je t'aimes   
58                                Je t'admires   
59                                  Je t'aimes   
60            Je te souhaites de récupérer tôt   
61                                  Vas t'en !   
62                                  Vas t'en !   
63                    Laisses moi tranquille !   
64                    Laisses moi tranquille !   
65                                  À l'aide !   
66                                       Feu !   
67                                    Arrête !   
68                         Appelle la police !   
69                           Mes voeux de noël   
70                      Mes voeux de nouvel an   
71                         Mes voeux de paques   
72                        Mes voeux de tabaski   
73                    Mes voeux d'anniversaire   

                                          wolof  
0                                        Merhbe  
1                                    Na nga def  
2                                  Na ngeen def  
3                                Salaam aleekum  
4                                 Jaam 

- Second file

In [22]:
path = 'data/additional_documents/omniglot/sentences_french_wolof_2.txt'

with open(path, 'r', encoding='utf-8') as f:
    
    # recuperate lines
    omn_2 = f.readlines()
    
# recuperate sentences
omn_2_ = {
    'french': [],
    'wolof': []
}

for omn in omn_2:
    
    omn = omn.split('–')
    
    sentences = [s.strip() for s in omn if s.strip() != '']
    
    omn_2_['wolof'].append(sentences[0])
    
    omn_2_['french'].append(sentences[1])

In [23]:
pd.options.display.max_rows = 74
omn_2_ = pd.DataFrame(omn_2_).head(74)

# print the first sentences from omniglot
omn_2_.head(74)

french                    wolof
0          Comment allez-vous ?           Na ngeen def ?
1                Bonne matinée.         Jaam nga fanane.
2                   Bonne nuit.           Fanaanal jaam.
3             À une autre fois.               Ba beneen.
4                 Je t'en prie.                   Agsil.
5              Je vous en prie.        Agsileen ak jaam.
6                       Pardon.                 Baal ma.
7                          Oui.                     Wau.
8                          Non.                 Deh-det.
9               Es-tu en paix ?            Jaam nga am ?
10             Comment vas-tu ?            Jaam nga am ?
11              Paix seulement.                Jaam rek.
12             Je suis en paix.                Jaam rek.
13                     Et toi ?                Yow nag ?
14      C'est comment ton nom ?          Naka-nga sant ?
15            D'où venez-vous ?        Fan ngeen joghe ?
16            Je viens des USA.   Maa ngi joghe les USA.
17           Parles-tu Anglais?         Deg nga Angale ?
18         Parles-tu Français ?        Deg nga Faranse ?
19  Je parle seulement anglais.    Angale rekk laa degg.
20     Je parle un peu anglais.  Degg naa tuuti Faranse.
21      Je ne parles pas Wolof.     Mahn deggumah Wolof.
22   Je ne parles pas Français.   Mahn deggumah Faranse.
23            Je n'entends pas.                 Degguma.
24               J'aimerais … .        Dama bahggoon … .
25                   Où est … ?              Fahn la … ?
26                Est-ce loin ?               Soreh na ?
27            C'est devant toi.               Cha kanam.
28                  Devant toi.               Cha kanam.
29                      Gauche.                Chammoon.
30                       Droit.                Ndeyjoor.
31                 Mais entre !           Dugghal waay !
32            Combine ça vaut ?               Lii naata?
33             C'est trop cher.           Seer na torob.

- Third file

In [24]:
path = 'data/additional_documents/omniglot/sentences_french_wolof_3.txt'

with open(path, 'r', encoding='utf-8') as f:
    
    # recuperate lines
    omn_3 = f.readlines()
    
# recuperate sentences
omn_3_ = {
    'french': [],
    'wolof': []
}

for omn in omn_3:
    
    omn = omn.split('\t')
    
    sentences = [s.strip() for s in omn if s.strip() != '']
    
    omn_3_['wolof'].append(sentences[0])
    
    omn_3_['french'].append(sentences[1])
      
        

In [25]:
pd.options.display.max_rows = 74
omn_3_ = pd.DataFrame(omn_3_).head(74)

# print the first sentences from omniglot
omn_3_.head(74)

french                             wolof
0             Que la paix soit avec toi.                 Salaam maaleekum.
1       Que la paix soit avec toi aussi.                  Maaleekum salaam
2                        Es-tu en paix ?                     Jaama ngaam ?
3                        Paix seulement.                        Jamma rek.
4                Comment va ta famille ?                  Ana waa kër gi ?
5    Où sont les membres de ta famille ?                  Ana waa kër gi ?
6                       Ils sont là-bas.                         Ñunga fa.
7             J'espère qu'ils vont bien.                 Mbaa defuñu dara.
8               Rien ne va mal avec eux.                 Mbaa defuñu dara.
9                    Non, ils vont bien.             Déedéet, defuñu dara.
10              Rien ne va mal chez-eux.             Déedéet, defuñu dara.
11         Comment se passe le travail ?                  Naka ligéey bi ?
12             J'y suis avec, pas à pas.  Maangi ci kowam, ndanka, ndanka.
13         J'y suis avec, petit à petit.  Maangi ci kowam, ndanka, ndanka.
14                      Comment vas-tu ?                       Nanga def ?
15                      Comment vas-tu ?                         Noo def ?
16  Comment vont les gens de la maison ?                 Naka waa kër ga ?
17               Comment va la famille ?                 Naka njaboot gi ?
18                         Je vais bien.                    Maangi fi rek.
19        Qu'est-ce que tu as rapporté ?                     Lan nga indi?
20          J'ai rapporté des nouvelles.                  Xibaar laa indi.
21               Je suis dans la maison.                 Maangi ci nég bi.
22               Ils se tiennent dehors.              Ñungi taxaw ci biti.
23         As-tu passé la nuit en paix ?                Jaama nga fanaan ?
24         Comment se passe la matinée ?                   Naka subba si ?
25             La matinée se passe bien.               Subba sangi fi rek.
26      As-tu passé la matinée en paix ?                   Jaama nga endu?
27       Comment se passe l'après-midi ?                   Naka bëcëk bi ?
28           L'après-midi se passe bien.              Bëcëk baangi fi rek.
29         Comment se passes la soirée ?                   Naka ngoon si ?
30              La soirée se passe bien.              Ngoon saangi fi rek.
31            Comment se passe la nuit ?                   Naka guddi gi ?
32                La nuit se passe bien.               Guddi gaangi fi rek
33                          Comment ...?                         Noo ... ?

- Let us retrieve sentences, that was created by internet users in our following platform [addition_sentences_platform](https://french-wolof-translation.streamlit.app/), from our MongoDB Atlas Database.

In [26]:
# initialize the path to the csv files
sentences_path = 'data/additional_documents/hugging_face/wolof_french.csv'
deleted_path = 'data/additional_documents/hugging_face/deleted.csv'

# initialize the server uri and database name
uri = "mongodb+srv://oumar199:Jacksparrow360@woloftranslationcluster.u0gk7.mongodb.net/?retryWrites=true&w=majority"
# uri = "mongodb+srv://oumarkanetest:Jacksparrow360__@woloftranslationcluster.u0gk7.mongodb.net/?retryWrites=true&w=majority"
database_name = 'WolofTranslation'

# initialize the database manager 
database_manager = TranslationMongoDBManager(uri, database_name)


# save locally the data sets
database_manager.save_data_frames(sentences_path, deleted_path)

hug_sents = pd.read_csv(sentences_path)

In [27]:
hug_sents.head()

french  \
0                   J'arrive tout de suite chez toi.   
1  J'en suis sûr, cette photo ci c'est la photo p...   
2  Je vois devant moi une photo sur laquelle beau...   
3  Ceux-ci sont des personnes qui sont sortis pou...   
4  Je pense que la photo que je vois là, c'est un...   

                                               wolof  
0                       Léegui léegui ma egg sa kër.  
1  Waaw nataal bii nataal la boob ay nit ñu baree...  
2  Nataal bii maa ngi ciy janloog haa ay nit yu b...  
3  Lii, ay nit lañu yu génn di ñaxtu. Jëm yi nag ...  
4  Man de nataal bii ma gis nii, nataal la boo xa...

-------------------

Nous devons ajouter des espaces autour des expressions entre apostrophes.

In [28]:
# # rectifier les phrases avec la fonction suivante
# def rectify_apos(sentence: str): # with the help of chat gpt
    
#     return re.sub(r"(?<![\wàâçéèêëîïôûùüÿñæœ])'([^']*?)'(?![\wàâçéèêëîïôûùüÿñæœ])", r" '\1' ", sentence)



In [29]:
# # add modification to all sentences
# hug_sents['french'] = hug_sents['french'].apply(rectify_apos)
# hug_sents['wolof'] = hug_sents['wolof'].apply(rectify_apos)

In [30]:
# hug_sents.to_csv('verification.csv', index=False)

In [31]:
# # recuperate the sentences from the csv file
# hug_sents = pd.read_csv('verification.csv')

In [32]:
# # add the modification to the mongo database sentences according to their ids
# def add_modification(sentences: pd.DataFrame, database_manager: TranslationMongoDBManager):
    
#     for i in list(sentences.index):
        
#         # recuperate the sentences
#         french_sent = sentences.loc[i, 'french']
        
#         wolof_sent = sentences.loc[i, 'wolof']
        
#         # add the modification
#         database_manager.update_document(i, 
#                                          {
#                                                 'french': french_sent,
#                                                 'wolof': wolof_sent
#                                          })

# add_modification(hug_sents, database_manager)

------------

In [33]:
# # print some documents inside the sentences collection using the uri
# def write_documents(uri):
        
#     from pymongo import MongoClient
    
#     # connect to the database
#     client = MongoClient(uri)
    
#     # get the database
#     db = client['WolofTranslation']
    
#     # get the sentences collection
#     collection = db['sentences']
    
#     # recuperate some documents
#     documents = collection.find()
    
#     # write the documents in a file
#     for doc in documents:
        
#         print(str(doc))
#         print(len(documents))
            
#     # close the connection
#     client.close()
    
# write_documents(uri)


In [34]:
pd.options.display.max_rows = 74

hug_sents.head(74)

french  \
0                    J'arrive tout de suite chez toi.   
1   J'en suis sûr, cette photo ci c'est la photo p...   
2   Je vois devant moi une photo sur laquelle beau...   
3   Ceux-ci sont des personnes qui sont sortis pou...   
4   Je pense que la photo que je vois là, c'est un...   
5   Bonjour ! Ceci est une photo. Sur cette photo ...   
6   Ceci est une photo sur laquelle je vois un poi...   
7   Ceci est ce qu'on appelle une douche, qu'on a ...   
8   Sur cette photo il semble qu'il y est un table...   
9   Sur cette photo, c'est une personne de couleur...   
10  Jusqu'à présent, on voit sur la photo des sold...   
11  Ceci, cependant, est un bol. Il y a du sucre d...   
12  Sur cette photo, il y a d'une salle dans la qu...   
13  Ceci est un ancien milieu avec une constructio...   
14  Ceux-ci sont de vieilles cases à l'intérieur d...   
15  Sur cette photo ci, j'y aperçois du beurre ; i...   
16  Ceci est une bouche qu'on a conçue, dans laque...   
17  Ici, cependant, il semble qu'il y est une port...   
18  Sur ma photo qu'on m'a envoyée, il y a apparem...   
19  Ceux-là, cependant, sont des cases. Celle qui ...   
20  Sur cette photo se trouvent deux présidents. I...   
21  Oui encore, je vois que ceci est une automobil...   
22  Sur cette photo, il y a un homme et une femme,...   
23  Ceci est une tasse et une assiette. On y verse...   
24  Ceci est un lieu d'habitation qui contient un ...   
25  Oui, sur cette photo, c'est des portes en gris...   
26  Cela est une photo. Je vois, dessus, deux femm...   
27  Cela est ce qu'on appelle  'La tour la plus ha...   
28  Ceux-là, aussi, sont des gendarmes. Ils siègen...   
29  Ceux-là sont des femmes policières. Elles sont...   
30  Sur cette photo ci, cependant, il y a des pers...   
31  Oui le parent, je vois que ceci c'est une théi...   
32  Sur cette photo ci il y a une assurément une c...   
33  Sur la photo que vous m'avez envoyée j'y ai vu...   
34  Sur cette photo j'y ai vu une case qui se trou...   
35  Sur cette photo ci, on dirait des autochtones ...   
36  Sur cette photo ci cependant, il y a un panier...   
37  Sur cette photo, j'y vois quelque chose qui re...   
38  Sur la photo que vous m'avez envoyée, j'y ai v...   
39  Ici j'y ai vu deux assiettes blanches.Parmi le...   
40  Celui là, j'ai vu que c'est un garçon, debout ...   
41  Sur cette photo ci, j'y ai vu des chambres fai...   
42  Oui ça, il semble que ce soit une fleur, mais ...   
43  À l'intérieur de cette photo je vois beaucoup ...   
44  Je vois une large chambre avec un lit pour pas...   
45  Ceci ressemble à un bahut. Un bahut chocolat d...   
46  Je sens que ceux-là sont, vraisemblablement, d...   
47  C'est des enfants qui jouent avec leurs jouets...   
48  C'est l'entrée de Louga. C'est à la frontière ...   
49  Ceux-là sont des garçons montés sur des chevau...   
50  Celui-là que tu vois c'est le dirigeant du pay...   
51  Cette photo ci est une photo sur laquelle il y...   
52  Sur cette photo, il y a une chose qui ressembl...   
53  Sur cette photo ci que je vois il y a des pers...   
54  Sur la photo que j'ai vue, j'y ai vu une jolie...   
55  Sur cette photo on voit ce qu'on appelle  'poi...   
56  Sur la photo que vous m'avez envoyée, j'ai vu,...   
57  Ceci est un four. C'est ce qu'on appelle une c...   
58  Sur la photo qu'on m'a envoyée, j'y ai vu un c...   
59  Sur cette photo, je suis face à une chaise pei...   
60  Ceci est un long bâtiment blanc. Il contient b...   
61  C'est des poissons, oui. Ils sont de couleur b...   
62  Ah sur cette photo ci cependant, il y a un poi...   
63  Ceci est un long et jolie bâtiment. On a vu de...   
64  Ceci se trouve dans les toilettes. <mask> cett...   
65  Ceux-ci sont des portes que les menuisiers mét...   
66  Sur la photo que vous m'avez envoyée, j'y ai v...   
67  Cela est une chaise de la rue  'la jardin publ...   
68  Ça c'est nos parents Laobés qui l'ont conçu. J...   
69  Ceci est un lieu d'habitation très charmant, t...   


Let us add them into the diagne's sentences and the version 4 of the corpora and remove duplicated rows.

- On corpora version 4

In [35]:
corpora_v6 = pd.concat((corpora_v4, omn_1_, omn_2_, omn_3_, hug_sents), axis=0)

# drop duplicated rows
print(sum(corpora_v4.duplicated()))

9


In [36]:
corpora_v6.drop_duplicates(inplace=True)

9 rows were deleted.

- On corpora version 5

In [37]:
ad_sentences = pd.concat((diagne_sentences, omn_1_, omn_2_, omn_3_, hug_sents), axis=0)

# drop duplicated rows
print(sum(ad_sentences.duplicated()))

6


In [38]:
ad_sentences.drop_duplicates(inplace=True)

6 rows were deleted.

### Web Scraping

This step involve to scrape some websites to obtain more sentences using `selenium` and `BeautifulSoup`. It will require to meticulously investigate each website and identify the elements to trigger and to extract. We will also need to identify the transformation to add to the different sentences. All the transformations, excepted the sentences' capitalization, are already implemented and can be directly used. 

We will scrape the following websites: 

- url1: [corporan.huma-num.fr](https://corporan.huma-num.fr/Lexiques/indexM.php?controle=afficheDico&action=main&ficXML=DicoWolof.xml&langue=Wolof)

In [54]:
url1 = "https://corporan.huma-num.fr/Lexiques/indexM.php?controle=afficheDico&action=main&ficXML=DicoWolof.xml&langue=Wolof"

#### Corporan.huma-num scraping

Let us add the necessary libraries.

In [1]:
from wolof_translate.utils.extract_new_sentences import NewSentenceExtraction
from wolof_translate.utils.sent_transformers import TransformerSequences
from selenium.webdriver.support import expected_conditions as EC
from wolof_translate.utils.improvements.end_marks import *
from selenium.webdriver.support.ui import WebDriverWait
from wolof_translate.utils.sent_corrections import *
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome import service
from selenium.webdriver.common.by import By
from urllib import request as rq
from selenium import webdriver
from bs4 import BeautifulSoup
from tqdm import tqdm
from typing import *
import pandas as pd

c:\Users\Oumar Kane\AppData\Local\pypoetry\Cache\virtualenvs\pytorch1-HleOW5am-py3.10\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


We need to identify the element containing the sentences. It is easy in that case since they are identified by their classes:

- The french sentences are identified by the `xe` class
- The wolof sentences by the `xv` class.

Since the website consists of a dictionary of word, we must click on one of them to display the sentences. The words' elements are not links but it use a ajax function. Then we must use trigger event to display the different pages. The words are represented by the `div` tag and each of them has a unique id which is simply the number of the word. We have `9965` words so the ids range from 1 to 9965.

Let us begin by initializing the drive. We will use the chrome driver in our case.

In [2]:
# initialize the option
options = webdriver.ChromeOptions()

# we will add the headless option which will not render the browser
options.add_argument('--headless')

# let us recuperate the service
s = service.Service('C:\Program Files\Chromedriver\chromedriver.exe')

# let us recuperate the driver
driver = webdriver.Chrome(service=s, options=options)



Let us request to go the website.

In [57]:
# send a get request to the website
driver.get(url1)

Let us initialize the classes.

In [2]:
# initialize the class map
class_map = {
    'xe': 'french',
    'xv': 'wolof'
}


Let us initialize the transformer.

In [3]:
transformer = TransformerSequences(remove_mark_space, delete_guillemet_space, add_mark_space)

Let us create a function which get recuperate the content and with beautiful soup recuperate the sentences. We will use an implicit wait at each time since we don't know what element to wait for: Not all pages contain sentences. We will wait 0.2 seconds before getting the sentences.

In [60]:
def get_sentences_from_page(driver: webdriver.chrome.webdriver.WebDriver, sentences: Dict[str, list], transformer: Union[TransformerSequences, None] = None, replaces: dict = {'…': '...'}, end_marks = ['.', '!', '?', '...']):
    
    # let us recuperate the content of the current page
    content = driver.page_source
    
    # recuperate the document object
    doc = BeautifulSoup(content, 'lxml')
    
    # recuperate the elements
    elements = {class__: doc.find_all('span', class_ = class__) for class__ in sentences}
    
    if elements != {key: [] for key in sentences}:
        
        # count the number of sentences that we got
        sent_count = len(elements[list(sentences)[0]])
        
        # for each group of sentences we will add some transformations
        for s in range(sent_count):
            
            # initialize the common end mark
            end_mark = None
            
            # recuperate the sentences and add to the dictionary of sentences
            for class__ in sentences:
                
                # recuperate the current sentence
                sentence = elements[class__][s].text.strip()
                
                # replace marks
                for replace in replaces:
                    
                    sentence = sentence.replace(replace, replaces[replace])
                
                if not sentence[-1] in end_marks:
                    
                    # add an end mark if the end mark is got from one of the previous sentences
                    if not end_mark is None:
                        
                        sentence += end_mark
                    
                    else: # add a period mark
                        
                        sentence += '.'
                
                else: # if an end mark is identified recuperated it as the end mark of the other sentences
                    
                    end_mark = sentence[-1]
                
                # capitalize the current sentence
                sentence = sentence[0].upper() + sentence[1:]
                
                # add transformations to the sentence
                if transformer: sentence = transformer(sentence)[0]
                
                # add the sentence to the dictionary of sentences
                sentences[class__].append(sentence)
            
    # return the sentences
    return sentences
    

In [ ]:
# calculate the approximate number of minutes
0.5*9956/60

82.96666666666667

Initialize the sentences 🛑.

In [4]:
# recuperate the saved sentences
scraped_sentences = pd.read_csv('data/extractions/new_data/scraped_sents.csv').to_dict('list')

# initialize the sentences
sentences = {key: scraped_sentences[class_map[key]] for key in class_map}

# current_id
current_id = 9836

# initialize the ids
word_ids = list(range(current_id, 9966))

Let us recuperate the sentences by clicking recursively at each word.

In [ ]:
# initialize the time sleep previously introduced
time_sleep = 0.6

# initialize a save step
save_step = 20

# recuperate the sentences of each word
for id in tqdm(word_ids):
        
    # click next to the word
    word = driver.find_element(By.ID, id)
    driver.execute_script('arguments[0].click();', word)
    
    # add a time sleep
    driver.implicitly_wait(time_sleep)
    
    # recuperate the sentences
    sentences = get_sentences_from_page(driver, sentences, transformer, replaces={'…': '...', '\xa0': ' ', 'qqn': "quelqu'un"})
    
    # save the sentences
    if id % save_step == 0:
        
        pd.DataFrame({value: sentences[key] for key, value in class_map.items()}).to_csv('data/extractions/new_data/scraped_sents.csv', index = False)
    
    

100%|██████████| 130/130 [03:41<00:00,  1.70s/it]


Not all sentences were recuperated. Let us make it again to recuperate additional sentences from the website.

Initialize the sentences 🛑.

In [68]:
# recuperate the saved sentences
scraped_sentences_2 = pd.read_csv('data/extractions/new_data/scraped_sents2.csv').to_dict('list')

# initialize the sentences
sentences_2 = {key: scraped_sentences_2[class_map[key]] for key in class_map}

# current_id
current_id = 300

# initialize the ids
word_ids = list(range(current_id, 9966))

Let us recuperate the sentences by clicking recursively at each word.

In [66]:
# initialize the time sleep previously introduced
time_sleep = 0.6

# initialize a save step
save_step = 20

# recuperate the sentences of each word
for id in tqdm(word_ids):
        
    # click next to the word
    word = driver.find_element(By.ID, id)
    driver.execute_script('arguments[0].click();', word)
    
    # add a time sleep
    driver.implicitly_wait(time_sleep)
    
    # recuperate the sentences
    sentences_2 = get_sentences_from_page(driver, sentences_2, transformer, replaces={'…': '...', '\xa0': ' ', 'qqn': "quelqu'un"})
    
    # save the sentences
    if id % save_step == 0:
        
        pd.DataFrame({value: sentences_2[key] for key, value in class_map.items()}).to_csv('data/extractions/new_data/scraped_sents2.csv', index = False)
    
    

100%|██████████| 9666/9666 [5:19:39<00:00,  1.98s/it]   


Let us take concatenate the two data frames and drop duplicated rows.

In [70]:
# concatenate the translations
scraped_sentences = pd.concat((pd.DataFrame(scraped_sentences), pd.DataFrame(scraped_sentences_2)))

In [72]:
# drop duplicated translations
scraped_sentences.drop_duplicates(inplace=True)

Let us verify how many translations we have.

In [74]:
# print the number of new translations
scraped_sentences.shape[0]

9388

Let us save the result.

In [76]:
scraped_sentences.to_csv('data/extractions/new_data/scraped_sents.csv', index=False)

We obtained `9388` translations from the first scraped website. Let us now make pre-processing on it. We will based on the following strings to make it:
- The parentheses containing 'ou...' 
- The slashes '/'
- The parentheses: We mostly want to delete them all
- Replace 'qqch' by 'quelque chose'
- Replace ';.' by '.'
- Replace 'œ' by 'oe'
- Identify the sentence with only ')' but not '('.

Let us create a function which can recuperate the sentences with regular expressions and another function which can replace an expression by another.

In [45]:
# %%writefile wolof-translate/wolof_translate/utils/re_extract.py
from typing import *
import re

def extract_with_re(translations: pd.DataFrame, columns: list = [], regex: Union[str, None] = None, recup_csv: str = 're_extract.csv'):
    
    # get all columns if no column is given
    if not columns: columns = list(translations.columns)
    
    for column in columns:
        
        assert column in set(translations.columns)
    
    # if not regular expression is given then return in the csv file all the sentences
    if not regex is None:
        
        # initialize the dictionary of the concerned sentences
        re_sents = {
            column: [] for column in columns
        }
        
        # at each index we will verify if a column respect the regular expression
        for i in range(translations.shape[0]):
            
            # make verification for each column
            re_true = False
            
            for column in columns:
                
                if re.match(regex, translations.loc[i, column]):
                    
                    re_true = True
                
            # add the line inside the set of translations to investigate
            if re_true:
                
                for column in columns:
                        
                        re_sents[column].append(translations.loc[i, column])
                
                # remove the sentences from the DataFrame
                translations.drop(index=[i], inplace=True)
            
        # save the resulted sentences in order to modify (it will wait until you finish the modifications)
        re_sents = pd.DataFrame(re_sents)
        
        print("You recuperated the following sentences:")
        print(re_sents)
        
        re_sents.to_csv(recup_csv, index=False)
        
        alert_ = ''
        
        while True:
            
            finish = input(f"{alert_}Provide Yes(y) if you finish and No(n) if not yet!")
            
            if finish == 'y':
                
                break
            
            elif finish != 'n':
                
                alert_ = "You cannot provide a command which is different from y (for Yes) and n (No)"
            
        # recuperate the modifications
        re_sents_2 = pd.read_csv(recup_csv)
        
        # add the sentences inside the original data frame and return the results
        translations = pd.concat((re_sents_2, translations))
        
        translations.index = range(translations.shape[0])
        
        return translations, re_sents_2
    
    return None
    
def replace_expression(translations: pd.DataFrame, columns: list = [], regex: Union[str, None] = None, new_expression: str = ''):
    
    # get all columns if no column is given
    if not columns: columns = list(translations.columns)
    
    for column in columns:
        
        assert column in set(translations.columns)
    
    # if not regular expression is given then return in the csv file all the sentences
    if not regex is None:
        
        # initialize the dictionary of the concerned sentences
        re_sents = {
            column: [] for column in columns
        }
        
        # at each index we will verify if a column respect the regular expression before making replacement
        for i in range(translations.shape[0]):
            
            for column in columns:
                
                expressions = re.findall(regex, translations.loc[i, column])
                
                if expressions != []:
                
                    translations.loc[i, column] = re.sub(regex, new_expression, translations.loc[i, column]).strip()

                    for column in columns:
                        
                        re_sents[column].append(translations.loc[i, column])
            
        # save the resulted sentences in order to modify (it will wait until you finish the modifications)
        re_sents = pd.DataFrame(re_sents)
        
        print("You recuperated the following sentences:")
        print(re_sents)
    
        return translations, re_sents
    
    return None

- Let us recuperate all translations containing parentheses with 'ou' and verify which of them will need to separated as multiple translations.

In [21]:
scraped_sentences, re_sents = extract_with_re(pd.DataFrame(scraped_sentences), regex='.*\(ou.*\).*')

You recuperated the following sentences:
                                               french                                      wolof
0   Je m'occupe de toi; je suis à toi. (ou encore)...                            Maa ngi ci yow.
1               C'est bien (ou bien) d'accord; ça va.                                   Baax na.
2   Il est bel et bien au courant (ou bien) il l'a...                    Yég na ko ba bëgga dee.
3                C'est pareil (ou bien) c'est unique.                                   Benn la.
4    Ils sont semblables (ou bien) ils ne font qu'un.                                 Benn lañu.
..                                                ...                                        ...
27         Être soupe au lait (ou bien) être frustré.                                  Tàng xol.
28                                       De bon cœur.  Ci xol bu sedd (ou bien) ci xol bu tàlli.
29       Vous êtes égaux (ou bien) vous êtes pareils.                                 

- Let us recuperate all translations containing slashes.

In [34]:
scraped_sentences, re_sents = extract_with_re(scraped_sentences, regex='.*(/).*')


You recuperated the following sentences:
                                              french                                              wolof
0  Qu'est-ce qui te prend ? / qu'est-ce qui t'arr...                                 (loc.) Lu la dal ?
1  Fais des boulettes plus grosses / fais davanta...                                    Yokkal dank yi.
2    Oh la, Omar ! / Arrête, Omar ! (Tu as fini ?) .                                         Eey, Omar.
3  J'en ai plus que toi / j'en ai un plus grand (...                                      Maa la ëpple.
4                Le voilà ! / Voilà / nous-y voilà !                                  (Lov.)Mu ngoogu !
5  Celui qui meurt au marché fait lui-même son an...  Ku dee marse, yaa tàgge sa bopp // ku dee ca j...
6  Il n'a pas mangé / il n'est pas en train de ma...                                            Lekkul.
7  Je n'ai pas mangé / je ne suis pas en train de...                                 Lekkuma lekkul ma.


- Separate in multiple ones the translations with parentheses

In [37]:
scraped_sentences, re_sents = extract_with_re(scraped_sentences, regex='.*\(.*\).*')

You recuperated the following sentences:
                                                french                                              wolof
0        Ces touffes (de cheveux), c'est leur coutume.                            Jubb yii, seen aada la.
1    Avant de tirer sur une bête, je vois d'abord s...  Bala may fital aw rab, dinaa xool ndax mu ngi ...
2       L'interdiction est temporaire (ne durera pas).                                   Aaye bi du yàgg.
3    Il prête sa charrette (à qui veut) uniquement ...  Li muy abalaate saretam bi yépp dey, bëgga fal...
4                      Les enfants sont arrivés (ici).                                 Xale yi agsi nañu.
..                                                 ...                                                ...
167  J'ai appelé ce village Njar-Meew (lait coupé) ...  Lu naqari la mu ma doon def, di ma ko yéjje, m...
168  Il dit qu'on a libéré les invités (ils peuvent...                           Mu ne yewwi nañu gan yi.
169  

- Delete parentheses

In [38]:
scraped_sentences, re_sents = replace_expression(scraped_sentences, regex='\(.*\)')

You recuperated the following sentences:
                                                french                                              wolof
0                    Ces touffes , c'est leur coutume.                            Jubb yii, seen aada la.
1    Avant de tirer sur une bête, je vois d'abord s...  Bala may fital aw rab, dinaa xool ndax mu ngi ...
2                      L'interdiction est temporaire .                                   Aaye bi du yàgg.
3     Il prête sa charrette  uniquement pour être élu.  Li muy abalaate saretam bi yépp dey, bëgga fal...
4                           Les enfants sont arrivés .                                 Xale yi agsi nañu.
..                                                 ...                                                ...
168                 J'ai appelé ce village Njar-Meew .  Lu naqari la mu ma doon def, di ma ko yéjje, m...
169                Il dit qu'on a libéré les invités .                           Mu ne yewwi nañu gan yi.
170  

- Replace 'qqch' by 'quelque chose'

In [47]:
scraped_sentences, re_sents = replace_expression(scraped_sentences, regex='qqch', new_expression='quelque chose')


You recuperated the following sentences:
                                               french                                              wolof
0   Il y a quelque chose  dans mes habits; tiens l...  Am na luy dox ci sama yére yi; téyeel ma xale ...
1   Dis-moi quelque chose qui puisse apporter la p...         Wax ma lu mëna amal jàmm ci sunu réew mi !
2   Je pensais qu'il m'appelait pour quelque chose...   Dama defe woon ne lu am-maanaa la ma doon wooye.
3   Le réparateur est arrivé. Qui aurait quelque c...        Baay-jagal dikk na. Ku amoon looy defarlu ?
4   Ses propos ont été brefs; lui aurais-tu fait q...       Waxam ji dafa bar; xanaa danga ko def dara ?
..                                                ...                                                ...
42  Quand on fait quelque chose, il est normal d'e...                            Kuy xalam, di ci jaayu.
43  Quand on reçoit quelque chose d'une personne q...  Bu la ku xér di may, sa xol sedd; waaye bu nge...
44  Ce dont on

- Replace ';.' by '.'

In [49]:
scraped_sentences, re_sents = replace_expression(scraped_sentences, regex=';\.', new_expression='.')

You recuperated the following sentences:
                                                french                                              wolof
0    Il y a quelque chose  dans mes habits.tiens l'...  Am na luy dox ci sama yére yi; téyeel ma xale ...
1    Il y a quelque chose  dans mes habits.tiens l'...  Am na luy dox ci sama yére yi.téyeel ma xale b...
2    Ses propos ont été brefs.lui aurais-tu fait qu...       Waxam ji dafa bar; xanaa danga ko def dara ?
3    Ses propos ont été brefs.lui aurais-tu fait qu...        Waxam ji dafa bar.xanaa danga ko def dara ?
4    Ça, il faudra tout faire pour l'avoir, c'est q...  Lii dey, nanga ci gar sa bakkan.lu lay amal nj...
..                                                 ...                                                ...
443           Il est fâché.il ne veut même pas manger.                       Dafa aru; nanguwul sax lekk.
444           Il est fâché.il ne veut même pas manger.                        Dafa aru.nanguwul sax lekk.
445  

In [53]:
# function created to add correction 
# def correction(text: str):
    
#     charac = ''
    
#     for i in range(len(text[:-1])):
        
#         letter = text[i]
        
#         if letter == '.' and re.match('[a-zA-Z]', text[i+1]):
            
#             charac = charac + '; '
        
#         else:
            
#             charac = charac + letter
        
#     return charac + text[-1]

- Replace 'œ' by 'oe'

In [58]:
scraped_sentences, re_sents = replace_expression(scraped_sentences, regex='œ', new_expression='oe')


You recuperated the following sentences:
                                               french                                       wolof
0   Une femme de moeurs légères ne se marie pas fa...                 Jigéen juy fo du yomba séy.
1                            Elle est ma jeune soeur.                               Sama rakk la.
2                                       De bon coeur.                            Ci xol bu tàlli.
3                                       De bon coeur.                             Ci xol bu sedd.
4                      Chante, nous ferons le choeur.                           Woyal, nu awu la.
..                                                ...                                         ...
93              Ton souhait ne te vient pas du coeur.                Sa yéene ji àggul ci sa xol.
94                           Coupe le jusqu'au coeur.                   Gor ko ba àgg ca yeññ wa.
95  Va jeter un coup d'oeil pour voir s'il est rév...            Demal yër ba

- Identify translations with only a closing parentheses

In [59]:
scraped_sentences, re_sents = extract_with_re(scraped_sentences, regex='.*\).*')


You recuperated the following sentences:
                                               french                                              wolof
0   La marmite, si elle doit être délicieuse, quan...                Cin, su naree neex, bu baxee, xeeñ.
1        L'homme et ses désirs, Dieu et sa décision).              Nit ak bëgg-bëggam, Yàlla ak dogalam.
2   C'est avec l'esprit avec lequel tu as creusé l...     Xel mi nga gase teen bi la ci keneen di naane.
3   Une langue ne mange pas son semblable, si on n...           Làmmiñ du lekk morom ma, te toggeesu ko.
4   Si ton talent de cavalier te pousse à monter s...  Su la mën ngawar jayee ba nga mafñàndum saaw, ...
..                                                ...                                                ...
26                      Ton corps est-il en paix ?) .                            Sa yaram jàmm bonjour !
27  Généreux, avec tes biens) sois généreux, mais ...                               Yéwén : ci sa alal !
28  Qui a broy

Let us save the sentences and delete the space between a point or a comma and the word behind them. 

In [60]:
scraped_sentences.to_csv('data/extractions/new_data/scraped_sents.csv', index=False)

Let us add the scraped sentences inside a new collection and add it also the translations from the already existing collection.

In [39]:
scraped_sentences = pd.DataFrame(scraped_sentences)

database_manager.insert_documents([{
        '_id': id,
        'french': scraped_sentences.loc[id, 'french'],
        'wolof': scraped_sentences.loc[id, 'wolof'],
    } for id in scraped_sentences.index], 'sentences_plus')

Let us insert inside the collection the translations from the sentences collection.

In [40]:
hug_sents.index = range(scraped_sentences.shape[0], scraped_sentences.shape[0] + hug_sents.shape[0])
database_manager.insert_documents([{
        '_id': id,
        'french': hug_sents.loc[id, 'french'],
        'wolof': hug_sents.loc[id, 'wolof'],
    } for id in hug_sents.index], 'sentences_plus')

### Removing duplicated rows (advanced) and adding transformations

---------------

#### Without scraped sentences

Let us consider only the fourth end mark adding's method and verify if we have duplicated rows.

- Corpora v6

In [39]:
french_sents = corpora_v6['french'].to_list()

wolof_sents = corpora_v6['wolof'].to_list()

french_sents = add_end_mark(french_sents, end_mark_to_remove='!')

wolof_sents = add_end_mark(wolof_sents, end_mark_to_remove='!')

corpora_v6_end = pd.DataFrame({'french': french_sents, 'wolof': wolof_sents})

In [40]:
duplicated = corpora_v6_end.duplicated()

sum(duplicated)

5

We obtain 5 duplicated rows. Let us recuperate their indexes.

In [41]:
dup_indexes = duplicated[duplicated == True].index

In [42]:
dup_indexes

Int64Index([1426, 1595, 2239, 2241, 2365], dtype='int64')

Let us remove those indexes from the corpora.

In [43]:
corpora_v6.drop(index = dup_indexes, inplace=True)

- Diagne's sentences

In [44]:
french_sents = ad_sentences['french'].to_list()

wolof_sents = ad_sentences['wolof'].to_list()

french_sents = add_end_mark(french_sents, end_mark_to_remove='!')

wolof_sents = add_end_mark(wolof_sents, end_mark_to_remove='!')

diagne_end = pd.DataFrame({'french': french_sents, 'wolof': wolof_sents})

In [45]:
duplicated = diagne_end.duplicated()

sum(duplicated)

5

We obtain 5 duplicated rows. Let us recuperate their indexes.

In [46]:
dup_indexes = duplicated[duplicated == True].index

In [47]:
dup_indexes

Int64Index([544, 713, 1357, 1359, 1483], dtype='int64')

Let us remove those indexes from the corpora.

In [48]:
ad_sentences.drop(index = dup_indexes, inplace=True)

----------------------------

#### With 3000 scraped sentences 

Let us add 3000 scraped sentences into the different datasets.

In [56]:
ad_sentences = pd.read_csv('data/extractions/new_data/ad_sentences.csv')
corpora_v6 = pd.read_csv('data/extractions/new_data/corpora_v6.csv')

In [57]:
shape_1 = ad_sentences.shape[0]

In [58]:
# inside diagne's sentences
add_sentences = pd.concat((ad_sentences, pd.DataFrame(scraped_sentences).head(3000)))

# inside the corpora
corpora_v7 = pd.concat((corpora_v6, pd.DataFrame(scraped_sentences).head(3000)))

# inside diagne's sentences (we want 5000 translations for diagne's sentences)
# ad_sentences = pd.concat((ad_sentences, pd.DataFrame(scraped_sentences).sample(3000 - shape_1)))


In [59]:
add_sentences.index = range(add_sentences.shape[0])
corpora_v7.index = range(corpora_v7.shape[0])

Let us consider only the fourth end mark adding's method and verify if we have duplicated rows.

- Corpora v7

In [60]:
french_sents = corpora_v7['french'].to_list()

wolof_sents = corpora_v7['wolof'].to_list()

french_sents = add_end_mark(french_sents, end_mark_to_remove='!')

wolof_sents = add_end_mark(wolof_sents, end_mark_to_remove='!')

corpora_v7_end = pd.DataFrame({'french': french_sents, 'wolof': wolof_sents})

In [61]:
duplicated = corpora_v7_end.duplicated()

sum(duplicated)

13

We obtain 5 duplicated rows. Let us recuperate their indexes.

In [62]:
dup_indexes = duplicated[duplicated == True].index

In [63]:
dup_indexes

Int64Index([1425, 1593, 2069, 2235, 2237, 2360, 3147, 3166, 3893, 4453, 4766,
            5539, 5725],
           dtype='int64')

Let us remove those indexes from the corpora.

In [64]:
corpora_v7.drop(index = dup_indexes, inplace=True)

- Diagne's sentences

In [65]:
french_sents = add_sentences['french'].to_list()

wolof_sents = add_sentences['wolof'].to_list()

french_sents = add_end_mark(french_sents, end_mark_to_remove='!')

wolof_sents = add_end_mark(wolof_sents, end_mark_to_remove='!')

diagne_end = pd.DataFrame({'french': french_sents, 'wolof': wolof_sents})

In [66]:
duplicated = diagne_end.duplicated()

sum(duplicated)

13

We obtain 5 duplicated rows. Let us recuperate their indexes.

In [67]:
dup_indexes = duplicated[duplicated == True].index

In [68]:
dup_indexes

Int64Index([543, 711, 1187, 1353, 1355, 1478, 2265, 2284, 3011, 3571, 3884,
            4657, 4843],
           dtype='int64')

Let us remove those indexes from the corpora.

In [69]:
add_sentences.drop(index = dup_indexes, inplace=True)

----------------------------

#### With 5000 scraped sentences 

Let us add 5000 scraped sentences into the different datasets.

In [70]:
ad_sentences = pd.read_csv('data/extractions/new_data/ad_sentences.csv')
corpora_v6 = pd.read_csv('data/extractions/new_data/corpora_v6.csv')

In [71]:
shape_1 = ad_sentences.shape[0]

In [72]:
# inside diagne's sentences
addd_sentences = pd.concat((ad_sentences, pd.DataFrame(scraped_sentences).head(5000)))

# inside the corpora
corpora_v8 = pd.concat((corpora_v6, pd.DataFrame(scraped_sentences).head(5000)))

# inside diagne's sentences (we want 5000 translations for diagne's sentences)
# ad_sentences = pd.concat((ad_sentences, pd.DataFrame(scraped_sentences).sample(3000 - shape_1)))


In [73]:
addd_sentences.index = range(addd_sentences.shape[0])
corpora_v8.index = range(corpora_v8.shape[0])

Let us consider only the fourth end mark adding's method and verify if we have duplicated rows.

- Corpora v8

In [74]:
french_sents = corpora_v8['french'].to_list()

wolof_sents = corpora_v8['wolof'].to_list()

french_sents = add_end_mark(french_sents, end_mark_to_remove='!')

wolof_sents = add_end_mark(wolof_sents, end_mark_to_remove='!')

corpora_v8_end = pd.DataFrame({'french': french_sents, 'wolof': wolof_sents})

In [75]:
duplicated = corpora_v8_end.duplicated()

sum(duplicated)

14

We obtain 5 duplicated rows. Let us recuperate their indexes.

In [76]:
dup_indexes = duplicated[duplicated == True].index

In [77]:
dup_indexes

Int64Index([1425, 1593, 2069, 2235, 2237, 2360, 3147, 3166, 3893, 4453, 4766,
            5539, 5725, 7143],
           dtype='int64')

Let us remove those indexes from the corpora.

In [78]:
corpora_v8.drop(index = dup_indexes, inplace=True)

- Diagne's sentences

In [79]:
french_sents = addd_sentences['french'].to_list()

wolof_sents = addd_sentences['wolof'].to_list()

french_sents = add_end_mark(french_sents, end_mark_to_remove='!')

wolof_sents = add_end_mark(wolof_sents, end_mark_to_remove='!')

diagne_end = pd.DataFrame({'french': french_sents, 'wolof': wolof_sents})

In [80]:
duplicated = diagne_end.duplicated()

sum(duplicated)

14

We obtain 5 duplicated rows. Let us recuperate their indexes.

In [81]:
dup_indexes = duplicated[duplicated == True].index

In [82]:
dup_indexes

Int64Index([ 543,  711, 1187, 1353, 1355, 1478, 2265, 2284, 3011, 3571, 3884,
            4657, 4843, 6261],
           dtype='int64')

Let us remove those indexes from the corpora.

In [83]:
addd_sentences.drop(index = dup_indexes, inplace=True)

----------------------------

#### With 7000 scraped sentences 

Let us add 7000 scraped sentences into the different datasets.

In [98]:
ad_sentences = pd.read_csv('data/extractions/new_data/ad_sentences.csv')
corpora_v6 = pd.read_csv('data/extractions/new_data/corpora_v6.csv')

In [99]:
shape_1 = ad_sentences.shape[0]

In [100]:
# inside diagne's sentences
ad4_sentences = pd.concat((ad_sentences, pd.DataFrame(scraped_sentences).head(7000)))

# inside the corpora
corpora_v9 = pd.concat((corpora_v6, pd.DataFrame(scraped_sentences).head(7000)))

# inside diagne's sentences (we want 5000 translations for diagne's sentences)
# ad_sentences = pd.concat((ad_sentences, pd.DataFrame(scraped_sentences).sample(3000 - shape_1)))


In [101]:
ad4_sentences.index = range(ad4_sentences.shape[0])
corpora_v9.index = range(corpora_v9.shape[0])

Let us consider only the fourth end mark adding's method and verify if we have duplicated rows.

- Corpora v9

In [103]:
french_sents = corpora_v9['french'].to_list()

wolof_sents = corpora_v9['wolof'].to_list()

french_sents = add_end_mark(french_sents, end_mark_to_remove='!')

wolof_sents = add_end_mark(wolof_sents, end_mark_to_remove='!')

corpora_v9_end = pd.DataFrame({'french': french_sents, 'wolof': wolof_sents})

In [104]:
duplicated = corpora_v9_end.duplicated()

sum(duplicated)

16

We obtain 16 duplicated rows. Let us recuperate their indexes.

In [105]:
dup_indexes = duplicated[duplicated == True].index

In [106]:
dup_indexes

Int64Index([1425, 1593, 2069, 2235, 2237, 2360, 3147, 3166, 3893, 4453, 4766,
            5539, 5725, 7143, 8377, 8538],
           dtype='int64')

Let us remove those indexes from the corpora.

In [107]:
corpora_v9.drop(index = dup_indexes, inplace=True)

- Diagne's sentences

In [108]:
french_sents = ad4_sentences['french'].to_list()

wolof_sents = ad4_sentences['wolof'].to_list()

french_sents = add_end_mark(french_sents, end_mark_to_remove='!')

wolof_sents = add_end_mark(wolof_sents, end_mark_to_remove='!')

diagne_end = pd.DataFrame({'french': french_sents, 'wolof': wolof_sents})

In [109]:
duplicated = diagne_end.duplicated()

sum(duplicated)

16

We obtain 16 duplicated rows. Let us recuperate their indexes.

In [110]:
dup_indexes = duplicated[duplicated == True].index

In [111]:
dup_indexes

Int64Index([ 543,  711, 1187, 1353, 1355, 1478, 2265, 2284, 3011, 3571, 3884,
            4657, 4843, 6261, 7495, 7656],
           dtype='int64')

Let us remove those indexes from the corpora.

In [112]:
ad4_sentences.drop(index = dup_indexes, inplace=True)

----------------------------

#### With all scraped sentences 

Let us add all scraped sentences into the different datasets.

In [130]:
ad_sentences = pd.read_csv('data/extractions/new_data/ad_sentences.csv')
corpora_v6 = pd.read_csv('data/extractions/new_data/corpora_v6.csv')

In [131]:
shape_1 = ad_sentences.shape[0]

In [132]:
# inside diagne's sentences
ad5_sentences = pd.concat((ad_sentences, pd.DataFrame(scraped_sentences)))

# inside the corpora
corpora_v10 = pd.concat((corpora_v6, pd.DataFrame(scraped_sentences)))

# inside diagne's sentences (we want 5000 translations for diagne's sentences)
# ad_sentences = pd.concat((ad_sentences, pd.DataFrame(scraped_sentences).sample(3000 - shape_1)))


In [133]:
ad5_sentences.index = range(ad5_sentences.shape[0])
corpora_v10.index = range(corpora_v10.shape[0])

Let us consider only the fourth end mark adding's method and verify if we have duplicated rows.

- Corpora v10

In [134]:
french_sents = corpora_v10['french'].to_list()

wolof_sents = corpora_v10['wolof'].to_list()

french_sents = add_end_mark(french_sents, end_mark_to_remove='!')

wolof_sents = add_end_mark(wolof_sents, end_mark_to_remove='!')

corpora_v10_end = pd.DataFrame({'french': french_sents, 'wolof': wolof_sents})

In [135]:
duplicated = corpora_v10_end.duplicated()

sum(duplicated)

22

We obtain 22 duplicated rows. Let us recuperate their indexes.

In [136]:
dup_indexes = duplicated[duplicated == True].index

In [137]:
dup_indexes

Int64Index([ 1425,  1593,  2069,  2235,  2237,  2360,  3147,  3166,  3893,
             4453,  4766,  5539,  5725,  7143,  8377,  8538, 10626, 10714,
            10808, 10811, 11336, 12240],
           dtype='int64')

Let us remove those indexes from the corpora.

In [138]:
corpora_v10.drop(index = dup_indexes, inplace=True)

- Diagne's sentences

In [139]:
french_sents = ad5_sentences['french'].to_list()

wolof_sents = ad5_sentences['wolof'].to_list()

french_sents = add_end_mark(french_sents, end_mark_to_remove='!')

wolof_sents = add_end_mark(wolof_sents, end_mark_to_remove='!')

diagne_end = pd.DataFrame({'french': french_sents, 'wolof': wolof_sents})

In [140]:
duplicated = diagne_end.duplicated()

sum(duplicated)

22

We obtain 22 duplicated rows. Let us recuperate their indexes.

In [141]:
dup_indexes = duplicated[duplicated == True].index

In [142]:
dup_indexes

Int64Index([  543,   711,  1187,  1353,  1355,  1478,  2265,  2284,  3011,
             3571,  3884,  4657,  4843,  6261,  7495,  7656,  9744,  9832,
             9926,  9929, 10454, 11358],
           dtype='int64')

Let us remove those indexes from the corpora.

In [143]:
ad5_sentences.drop(index = dup_indexes, inplace=True)

-------------------

Apply transformations on all sentences.

In [144]:
# apply the transformations to all the sentences
def correction(text: str):
    
    text = transformer(text)[0]
    
    return text

# add corrections to the translations
ad5_sentences['french'] = ad5_sentences['french'].apply(correction)
ad5_sentences['wolof'] = ad5_sentences['wolof'].apply(correction)

corpora_v10['french'] = corpora_v10['french'].apply(correction)
corpora_v10['wolof'] = corpora_v10['wolof'].apply(correction)

# ad4_sentences['french'] = ad4_sentences['french'].apply(correction)
# ad4_sentences['wolof'] = ad4_sentences['wolof'].apply(correction)

# corpora_v9['french'] = corpora_v9['french'].apply(correction)
# corpora_v9['wolof'] = corpora_v9['wolof'].apply(correction)

# addd_sentences['french'] = addd_sentences['french'].apply(correction)
# addd_sentences['wolof'] = addd_sentences['wolof'].apply(correction)

# corpora_v8['french'] = corpora_v8['french'].apply(correction)
# corpora_v8['wolof'] = corpora_v8['wolof'].apply(correction)

# add_sentences['french'] = add_sentences['french'].apply(correction)
# add_sentences['wolof'] = add_sentences['wolof'].apply(correction)

# corpora_v7['french'] = corpora_v7['french'].apply(correction)
# corpora_v7['wolof'] = corpora_v7['wolof'].apply(correction)

# ad_sentences['french'] = ad_sentences['french'].apply(correction)
# ad_sentences['wolof'] = ad_sentences['wolof'].apply(correction)

# corpora_v6['french'] = corpora_v6['french'].apply(correction)
# corpora_v6['wolof'] = corpora_v6['wolof'].apply(correction)

# diagne_sentences['french'] = diagne_sentences['french'].apply(correction)
# diagne_sentences['wolof'] = diagne_sentences['french'].apply(correction)

# corpora_v4['french'] = corpora_v4['french'].apply(correction)
# corpora_v4['wolof'] = corpora_v4['french'].apply(correction)

# print clearly the results
pd.options.display.max_rows = 74
ad_sentences.sample(74)


french  \
1023                      C'est un autre qui est venu ?   
1746                   J'arrive tout de suite chez toi.   
1687                                   Es-tu en paix  ?   
1191                                        Où est-ce ?   
1565  Que tu partes ou que tu ne partes pas il viendra.   
1629                                       Bonne soirée   
148         C'est cet autre cheval là-bas qui est bon !   
1092                     Ici, jusqu'à ce qu'il vienne !   
937                                C'est là seulement !   
1740                        L'après-midi se passe bien.   
704                                Tu pries pour quoi ?   
383                               Personne n'était venu   
1718                                   Ils sont là-bas.   
731                             C'est un homme gentil !   
393                           Vous ne les aviez pas vus   
242                       J'ai vu la maison de son ami.   
1001               Mais, même moi, je ne viendrai pas !   
1289                 Je parle de ces autres individus !   
395                            Tu n'y avais vu personne   
740                              Il veut que tu viennes   
1667                           Laisses moi tranquille !   
1877  Oui sur cette photo ci aussi, j'y ai vu un bol...   
1450                       L'homme est allé aux champs.   
254                                Il a tué une lionne.   
85                                     Toute la chambre   
1793  C'est des enfants qui jouent avec leurs jouets...   
548                                      Tu as vu qui ?   
778                                         Nul n'a été   
1146                             Le voilà et le voilà !   
1207                         Donc, tu ne partiras pas ?   
333                                     Où a-t-il été ?   
717                                      À l'intérieur.   
223                       Tu es quel genre d'étudiant ?   
325                                          Dites-leur   
1924  Fannie Flono est ici et elle va nous parler de...   
3                    Il n'a pas encore pris de contacts   
1138                      Hier, aujourd'hui, avant-hier   
372                                  C'est moi qui pars   
248              Tu parles de la ville de quel Sérère ?   
473                               Celui-ci serait parti   
918                            Vois Moussa simplement !   
199                             Tu vois, ce garçon-là ?   
757                     La réunion c'est à l'intérieur.   
1852  J'ai vu à l'intérieur de la photo des ustensil...   
565                       Tous ceux-là doivent partir !   
116                           Aucune clef n'est égarée.   
280                 C'est ce qu'il a dit qui est vrai !   
1566                   Il est venu hier et aujourd'hui.   
314                                             Viens !   
1129                            S'il veut qu'il entre !   
304                       C'est lorsque la femme arriva   
48                            Je parle de cet homme-ci.   
1923  On ne m'a jamais rien dit de rencontrer quelqu...   
375                                     L'homme cultive   
1516                    Je crois qu'il ne viendra pas !   
1584  Il t'a fait un cadeau pour que les enfants soi...   
1921     Le client nommé Cutty gagne 10 000 $ par mois.   
1194                          Tu parles de quels gens ?   
176                                    Je vois l'homme.   
767                                    Un homme n'a été   
1027                         Je veux que l'homme vienne   
1738                   As-tu passé la matinée en paix ?   
1062                       L'homme veut que tu viennes.   
1593  La dame voudrait bien que vous ayez mais aussi...   
1013                      L'homme que l'enfant a appelé   
346                                      Je ne veux pas   
1478                             C'est un homme gentil.   
261                  C'est un homme q

In [145]:
corpora_v6.sample(74)

french  \
596   Il partage l'ordinaire des Touareg qui accompa...   
1333                                      Je n'irai pas   
1703                                     Il est dehors.   
1774                                  Monte jusqu'ici !   
55                                Sans doute un jardin.   
387   Les outils aussi, ses instruments de chirurgie...   
1167                          C'est toi qui n'a pas été   
1245                          C'est toi qui serais venu   
1772                           Attends jusqu'à demain !   
2374  Cet autre qui est sorti n'est pas encore arrivé !   
687   Il m'est possible aujourd'hui de regretter d'a...   
1321                      S'il ne vient pas, il verra !   
1185                       C'est lorsque tu t'en allas.   
103   Au bord du socle en ciment qui servait de trot...   
1319             C'est lui qui n'est pas Laobe du Baol.   
1019                C'est un autre cheval que je veux !   
1786                                      Le voilà, là.   
635   Les routes, les chemins ne sont pas sûrs, il f...   
913                  Je parle de cette dame que voilà !   
195   Je ne m'en souviens pas, mais j'ai dû crier, h...   
1855                                         A Moussa !   
545   Moi, je ne sais rien de ma naissance (ce qui e...   
2543                                         Je t'aimes   
2426  Vas-y pour qu'il vienne, pour qu'il ne soit pl...   
22    L'odeur des corps aussi, le toucher, la peau n...   
2418                     Je veux un peu d'argent de toi   
282   Les lorgnons n'étaient déjà plus très courants...   
2762  Cette photo ci c'est une photo sur laquelle je...   
2219                                            Il part   
298   Je me souviens aussi d'avoir été pris par des ...   
464   Et son chien, nommé Polisson, une sorte de bra...   
572   Il prend le bateau de retour vers l'Afrique ju...   
1631                     L'homme est un Saint-Louisien.   
963                               Quel cheval veux-tu ?   
575   Peut-être espère-t-il, comme beaucoup de gens ...   
739   Même loin de Banso, mon père ne pouvait pas l'...   
2740  Oui ceci est comme je te l'avais dit seulement...   
148   Le jour suivant, les ouvrières avaient colmaté...   
1440                                    Nul n'est venu.   
2102               Les enfants sont arrivés, j'espère ?   
1176                                  L'homme est parti   
446   C'est à Bamenda que mon père emmène ma mère ap...   
400   Mais un vieil homme dépaysé, exilé de sa vie e...   
2480                           Que personne n'est parti   
584   C'est sans doute à ce moment-là que mon père t...   
937                               J'ai aperçu des gens.   
1140                          C'est un homme généreux !   
1029            Je parle de cet autre homme que voilà !   
2112   Par contre, cet homme qui s'exila ne revint pas.   
1580                    Sur ces entrefaites, je me tus.   
1118                    J'ai vu les enfants de la dame.   
2594                         Que la paix soit avec toi.   
2557                                Mes voeux de paques   
15    Dans la case que nous habitions (le mot case a...   
938                            Quel homme s'est égaré ?   
1005                       Aucune dame ne s'est égarée.   
246   L'odeur de la soupe d'arachide, du foufou, du ...   
951                     Quels couteaux se sont égarés ?   
2654  Cela est une photo. Je vois, dessus, deux femm...   
2661  Sur la photo que vous m'avez envoyée j'y ai vu...   
987                          Va voir tous les chevaux !   
2061                                          Tu pars ?   
534   L'Afrique à la fois sauvage et très humaine es...   
1100                          Ce n'est pas le tambour !   
1946                        C'est l'homme qui est venu.   
2706  On voit sur la photo beaucoup de personnes sor...   
816              S'exiler pour fuir les feux de brousse   
471   Sur la carte qu'il a établie lu

In [146]:
add_sentences.sample(74)

french  \
688                   Eh bien, est-ce qu'il est parti ?   
2829  Tant mieux si on pousse à l'action quelqu'un q...   
4051             Un produit qui éloigne les moustiques.   
1501         C'est Fatim, si on va au fond des choses !   
975                                           Tu pars ?   
3631                Cette fois-ci alors, c'est audible.   
4708  Elles ont formé un cercle et attendent que que...   
3468                                   Je suis fatigué.   
1334  J'aurais acheté le mouton de quelle autre pers...   
3086  Aujourd'hui, j'ai une forte envie de côtelette...   
3561               Il n'a plus de molaires pour mâcher.   
1708                                             Droit.   
7                                     Homme est parti !   
15                                 Tu sais, cet homme ?   
3417  Quand il était enfant, il n'acceptait pas de p...   
1188                    À qui as-tu donné de l'argent ?   
3066                        La maison n'a qu'une porte.   
517                               Te voilà debout, ici.   
4360                    Je lui ai décoché deux flèches.   
2423                  Astou est une ajaratu maintenant.   
1522  Certainement, c'est l'homme qui a dit qu'il es...   
2366    Tout ce dont tu auras besoin, il s'en occupera.   
3325  Il y a encore des griots qui peuvent te racont...   
1916              Je ne sais pas pourquoi c'est arrivé.   
1377  Des boeufs que tu vois dans cette ville, le pl...   
1739                    Comment se passe l'après-midi ?   
2006         Durer n'est pas du savon, mais il lessive.   
1113                             Il est là, peut-être !   
2484                C'est de toi qu'on parle au marché.   
3647  J'ai habité chez lui pendant un mois et il ne ...   
1268                           Quel moutons est égaré ?   
1247                    Je parle de cet enfant là-bas ?   
1468                              Je t'ai vu avec lui !   
3697         On ne peut pas comparer les deux affaires.   
3610                      Avez-vous entendu la cloche ?   
1581  L'homme est parti mais les enfants ne le sont ...   
4015  Chaque fois qu'arrive la saison des pluies, sa...   
1715                                    Paix seulement.   
4951                           C'est extrêmement lourd.   
2970  Elle pile l'épi de mil pour en extraire les gr...   
3915  Ce sont les Saint-Louisiens qui disent damaa ;...   
2104                                Le con de ta mère !   
2757           Une union où il y a une grande maturité.   
3125           Il vend des louches en gourde-calebasse.   
1465  Il a cherché à l'intérieur et à l'extérieur au...   
3074                           Mets les boyaux à part !   
1990  La meilleur attitude à avoir dans une réunion,...   
2433                           Tu peux parler avec lui.   
569       C'est celui-là celui-là l'un que je te donne.   
4144                         Fatou est allée au marché.   
1444  Vers cet autre qui est devant la porte de la m...   
2307            Il a abandonné les plaisirs terrestres.   
3585                          Vos préparatifs traînent.   
480                                     Il travaillait.   
4579                 Elle lui a cousu une robe de gaze.   
3752                         Il a un hématome à l'oeil.   
2372         Ce sont les soldats qui protègent le pays.   
2911                 Quand il arriva, tous se levèrent.   
1128              Qu'il entre à l'intérieur s'il veut !   
4774  La viande que tu as achetée a beaucoup de grai...   
809                                    Cherche l'autre.   
4205    Une culbute ne te débarrassera pas de tes poux.   
3278                 Se séparer en beauté, c'est mieux.   
3023  Il a une rage de dents ; il ne viendra pas tra...   
76                       Que j'attrape quelles vaches ?   
3153                       Il blague ; ne te fâche pas.   
94                                 Le mouton en entier.   
1070                      Un homme ve

In [147]:
corpora_v7.sample(74)

french  \
4347  Quand il est venu ici, c'est moi qui l'ai hébe...   
1035                                    C'est ton ami !   
4876       Qui a coupé un morceau du pain de l'enfant ?   
1878                           Si elle veut, bien sûr !   
4439                        Le fleuve entoure la ville.   
2102               Les enfants sont arrivés, j'espère ?   
3454   Nous nous relayons pour la préparation du repas.   
5858   Maintenant, il fait des efforts dans ses études.   
1656                           Moi-même je n'ai pas été   
3198                            Il est mon jeune frère.   
2155                    Quelles personnes sont venues ?   
5300  C'est là-bas que se retrouvent toutes les femm...   
3580                      Je ne peux pas te le refuser.   
2778  Sur la photo que vous m'avez envoyée, j'ai vu ...   
2659  Oui le parent, je vois que ceci c'est une théi...   
2610               Comment vont les gens de la maison ?   
3971        Il a quatre-vingts ans et toutes ses dents.   
2556                             Mes voeux de nouvel an   
2372             J'ai prêté le livre à cet homme parti.   
1167                          C'est toi qui n'a pas été   
5319  Ce n'est pas la peine de creuser, il faut l'ar...   
1571                                Ainsi, nul ne parle   
5549  Son grand-père faisait partie des autorités en...   
3420  Est-ce qu'injurier fait partie d'une bonne édu...   
887                         L'homme n'est pas mauvais !   
3352                                    C'est possible.   
1007                         Aucun mouton n'est arrivé.   
698   Pour un rien, un bol cassé, un mot de travers,...   
5762                Aujourd'hui, j'ai dîné tardivement.   
2178                         Tu parles de quel mouton ?   
3646                          C'est une personne rusée.   
1330                             Les femmes accepteront   
2917           Omar a fait quelque chose de scandaleux.   
3413                                   Voici ma maison.   
1290                                       Góor giy dem   
3419                  Il a mis trop de maquillage bleu.   
4187                Le vin de palme frais n'enivre pas.   
4741           Les belles dames vont épuiser ses biens.   
5460  C'est à moi qu'il lance des flèches, mais je n...   
3502                       Il l'accompagne en sourdine.   
3374  Omar est une de mes relations ; je peux lui de...   
3765         Un jour, tu sauras à quoi sert la famille.   
795   Je ne veux pas parler d'exotisme : les enfants...   
5368                           Je t'ai cherché partout.   
2555                                  Mes voeux de noël   
4000                   Il ne sait pas garder un secret.   
4530                        Jésus a ressuscité un mort.   
4582  Il avala le lait d'un trait et attendit la suite.   
2745  Sur cette photo ci, il y a des pierres qui son...   
3771  L'oeil ne porte pas mais il sait ce que la têt...   
5306            S'il pleut, je surseoirai à mon voyage.   
3417               Voilà un caillou à côté de ton pied.   
3249       Est-il nécessaire que nous allions le voir ?   
2603                                Non, ils vont bien.   
2609                                   Comment vas-tu ?   
2193                              Tu as été quelqu'un !   
3262            C'est un joueur de football talentueux.   
2966                             Mon Dieu, sauve-nous !   
3484                       Arrête de faire la navette !   
2864                                       Premier don.   
891                                       J'ai vu lion.   
3662             C'est ton hilaire usée qui te retarde.   
597   Tout le long de la route, il prend des photos ...   
4681              Et la promesse que tu m'avais faite ?   
3443                     Le relais est à quelle heure ?   
4627                        Astou écrase les arachides.   
2055                                     Oui celui-là !   
4653           C'est l'an prochain qu

In [148]:
addd_sentences.sample(74)

french  \
3694  Cherche un endroit à proximité de ton lieu de ...   
237                  Tu as vu le fils de quelle femme ?   
1427                              L'homme fit : pouah !   
3782  Quand vous serez sur le point de partir, vous ...   
1502                           C'est Fatim, peut-être !   
2362  Il ne suffit pas de vouloir partir, il faut po...   
3587                            Je pense qu'il partira.   
5099                                     Tu m'as collé.   
447                                     L'homme partira   
3955           Je me contente de ce que Dieu m'a donné.   
4602  Griffer l'eau, c'est ta poitrine qui en pâtira...   
6960           La pipe que tu lui as offerte est belle.   
4126               Ils voulaient exterminer notre race.   
3522                               Il fuit le policier.   
4121  Apporte-le chez le cordonnier pour qu'il le co...   
1376        L'homme voudrait voir celui qui était parti   
3113                 Mets-y des feuilles de Tinospora !   
5547                 Tu l'as terrassé, il t'a renversé.   
4213                          Je raccordais les cordes.   
4185             Est-ce que tu vas souvent à la plage ?   
6793                Fais attention au trou devant toi !   
2276                   Fais des boulettes plus grosses.   
1048                     Où est l'homme dont il parle ?   
4720     Nos liens de parenté s'arrêtent à Adam et Ève.   
6031                     Il n'en a fait qu'une bouchée.   
2374  On a réuni toutes les personnes ayant atteint ...   
6602  Il ne doit pas y avoir de moment d'inattention...   
6856  Si la souris brave le chat, c'est que la haie ...   
3163           Cueille la grappe qui est à côté de toi.   
1543  Je crois que ce n'est pas celui-ci, ce n'est p...   
2485                        Je ne dois rien à personne.   
6292       Nettoie le sang caillé avant de le soigner !   
3076  J'ai eu tant d'enfants de toi que mon appareil...   
4861  Il est honnête, c'est pour cela que j'accepte ...   
2235            Tellement... que tu ne peux t'imaginer.   
2363                             Tu as dit Omar ou... ?   
6701  Ceux qui ne sont pas égaux en salive ne doiven...   
527                                        En voilà un.   
1413  Tout ce verbiage, c'est pour que tu ne viennes...   
626                                 De quelle manière ?   
2140  On t'a chargé d'une responsabilité, il faudra ...   
2944                          À chacun sa constitution.   
6626    Il y a des racines qui guérissent la gingivite.   
5713                                Place-le plus haut.   
2654                            Tu le sais bel et bien.   
5597  Il dit que vous devez vous accommoder de cette...   
2433                           Tu peux parler avec lui.   
5068  Seule une personne qui a une famille nombreuse...   
3445               Dis-lui de rassembler la vaisselle !   
6726  Ñoom il s'est familiarisé avec les enfants, il...   
6697                    Tu es l'unique Dieu que existe.   
541                               Que je ne parte pas !   
4277               Tu mettras de côté deux sacs de mil.   
4783                               Ma lèvre est fendue.   
912                             L'homme n'est pas venu.   
1982                                       Premier don.   
6815  Quand des gens vivent ensemble, ils doivent êt...   
4341              Je veux sevrer Marie Emilie vendredi.   
5326  Aussi nombreux que puissent être les oiseaux, ...   
6480                           Trace une ligne courbe !   
6619                      Le train passe par le tunnel.   
584                           Tous lesquels as-tu vus ?   
3291                        Le francolin s'est envolée.   
3773  Quoi bon avoir beaucoup de mil si on n'y survi...   
884                                    Va jusqu'à lui !   
2154                    Avez-vous entendu le tonnerre ?   
6367  Celui qui se couche sur le dos pour pisser ser...   
6915                                 

In [149]:
corpora_v8.sample(74)

french  \
3882  Il est si charitable qu'il prend en charge tou...   
1527                          Cela même que tu as fait.   
948                    Quelles femmes se sont égarées ?   
6086                            Elle n'est plus vierge.   
3303  Ceux qu'on appelle Wolof actuelle-ment, il fut...   
7435  Fais attention de ne pas te cogner la tête con...   
2554                                Appelle la police !   
3062                            Je m'abandonne à Bamba.   
5331              Le riz est fermenté, ne le mange pas.   
6688                              Un pantalon en toile.   
3268  Celui qui ne permet pas de toucher aux feuille...   
2786  J'avais l'impression d'être le seul à avoir ce...   
3478  J'y suis allé quand je suis venu ici la premiè...   
2684  Sur la photo que vous m'avez envoyée, j'ai vu,...   
3332  C'est Aldemba que les enfants ont dessiné au mur.   
2571                                    Paix seulement.   
4182        On s'occupe de tout, sauf de l'habillement.   
7464               Il n'avait pas pris part au battage.   
89    Nous n'allions pas à l'école en Afrique. Nous ...   
7823  Il vaut mieux trahir celui qui t'a circoncis q...   
4122                               Fais-en cinq parts !   
2315                L'enfant n'a rien donné à celui-ci.   
7455  Ils ont mis à la mode les franges au bas des p...   
6484             Ne t'agrippe pas au pied de la table !   
7241  Ne pourrais-tu pas cacher le lait jusqu'à ce q...   
6059                            Il veut nous brouiller.   
1099                           Sois un être de raison !   
830                   Sur la route de Bamako à Aroundou   
4415                              J'enfant a fait caca.   
5301  Ñów il pleurait, disant qu'il faut absolument ...   
2884  L'oiseau ne dit pas la même chose quand il est...   
3246                                Fiche-moi la paix !   
1896                   À l'intérieur : où il fait clair   
225   Pour corser l'affaire il fallait donc, de temp...   
212   Chaque nuit, il parcourait la maison, sa torch...   
2466  Il t'a fait un cadeau pour que les enfants soi...   
4503  S'il y a une bonne entente entre vous, tout ma...   
7728                      Qu'as-tu à te couvrir ainsi ?   
3048  On attache le prépuce à l'habit du circoncis j...   
5362               D'un coup, il le dépeça entièrement.   
3435  Laisse-moi ça, je te laisse tout ce qui viendr...   
3067                           Apporte donc le cadeau !   
7244  Chaque fin de mois, il se cache du propriétair...   
280   La première fois que j'ai vu mon père, à Ogoja...   
3341                       Il est assis sous l'ébénier.   
1213                                 C'est lui qui aime   
4108  Apporte les ingrédients qui étaient dans la sa...   
2990                                     Se prostituer.   
1561                       Malheureusement, nul n'a été   
6671                 Mon chien a les oreilles écornées.   
7586                                 Il en veut à Omar.   
6370                                 Couvre le nombril.   
1388                  Je te parle à toi fils de Massar.   
2749  Sur cette photo, il y a un gendarme monté sur ...   
4810  On dirait qu'Omar, sa femme l'a cloué sur plac...   
6088                        En deux pas, il est arrivé.   
579   Alors qu'elle est à peine remise de son accouc...   
6213  Il a tué deux antilopes à raies blanchâtres et...   
2269  Les moutons sont peut-être déjà arrivés, mais ...   
5102              Cherche un chiffon, tu le calfeutres.   
925            Je parle de la personne qui est sortie !   
1689                         L'homme a vu cet autre-là.   
4469                            Je pense qu'il partira.   
5475          Ajoute au cheval du foin dans la musette.   
5808          Coupe les pétioles et pile les feuilles !   
1023          C'est une autre jeune fille que je veux !   
446   C'est à Bamenda que mon père emmène ma mère ap...   
5823  En cette fête traditionnelle, c

In [150]:
ad4_sentences.sample(74)

french  \
1446  C'est celui-là même devant le seuil de la maison.   
4856     Il a dégorgé toute la boisson qu'il avait bue.   
7169                                 Il est trop avare.   
3540                                   C'est bien lui !   
7607                       Ceux qui sont à l'intérieur.   
1618                                    Mon nom est ...   
2455                                    Visage austère.   
4865  Il n'y a pas beaucoup de femmes qui peuvent ha...   
734                                      Qui as-tu vu ?   
8366    Une luxation peut faire pleurer même un adulte.   
6597             Prends une partie des épis à griller !   
4664                        Va m'acheter du coton filé.   
5083  Quand celui qui apporte le sable viendra, tu l...   
6499                             Il voulait te tromper.   
4456  Tous ceux qui entendent cette chanson claquent...   
2666  Si le germe n'est pas tombé, le fruit peut ger...   
2040  Pour répondre, encore faut-il être présent ; p...   
2278                                      Oh la, Omar !   
307                                 L'homme serait mort   
940                   La chose est d'un blanc éclatant.   
3217  Je lui ai tiré les vers du nez pour savoir ce ...   
1894  Ceci est, cependant, une porte conçue avec du ...   
4303  Quand ils se ruèrent l'un sur l'autre, on leur...   
2402       Abdou Diambar te dit : – As-tu prié ou non ?   
6061   Apporte de l'eau pour que j'y trempe les plants.   
134                     Cherche une autre jeune fille !   
1620                                    D'où viens-tu ?   
6776                       Cela n'en vaut pas la peine.   
145                          Il parle de l'autre homme.   
6686                   Il est habile de la main gauche.   
6860        Ça, je ne peux pas le vivre sans rien dire.   
2690                            L'âne refuse de partir.   
2003         La chèvre ne glane pas de jujubes la nuit.   
234                  Je reconnais les vaches d'Europe !   
7824  Est-ce que tu ne donnes pas de repos à ton che...   
1763  Ici, cependant, il semble qu'il y est une port...   
1724                          J'y suis avec, pas à pas.   
569       C'est celui-là celui-là l'un que je te donne.   
6277       Si lourd soit-il, tu le porteras sur le dos.   
1718                                   Ils sont là-bas.   
1256                             J'ai aperçu un baobab.   
5549             Actuellement, on échange les coutumes.   
5994             Il brigue un portefeuille ministériel.   
8307  La parole est comme une balle de fusil, si ell...   
1130              S'il veut qu'il entre à l'intérieur !   
7951                           C'est tout à fait clair.   
3741                                Le train a démarré.   
5477  Un commerçant bradait des moustiquaires, j'en ...   
7853          Les enfants tendent un piège aux pigeons.   
2160       Tu enlèves les feuilles qui sont en surface.   
6953  La demande en mariage se fera après la prière ...   
8844    Dès que la piqûre pénétra, il hurla de douleur.   
7497             Le pays ressemblait à un arbre blessé.   
3536                            Le couteau est émoussé.   
3481        La sauce est épaisse ; rajoutes-y de l'eau.   
2561                     Le relais est à quelle heure ?   
3545                   Prends tes affaires et va-t'en !   
6602  Il ne doit pas y avoir de moment d'inattention...   
205                              Ils ont été bûcherons.   
8875                Ne mets pas ton doigt à la bouche !   
6732  La fourmi que tu as tuée est une créature de D...   
4506                     Celui-ci est bien plus rapide.   
8645      Il te remercie de ce que tu as fait pour lui.   
890                            Attends jusqu'à demain !   
6115    Tu vois les scorpions marcher au clair de lune.   
7086  Il est tombé sur le sac, écrasant toutes les t...   
3834                          Battre froid à quelqu'un.   
2378  Moi vraiment ce que j'ai aperçu

In [151]:
corpora_v9.sample(74)

french  \
8239                                        Il t'envie.   
4835                                   Que me veux-tu ?   
8379             Le pays ressemblait à un arbre blessé.   
3075                             Le lait n'est pas pur.   
8202       Quand le gros tambour fit boum, il sursauta.   
7917  Elle est mariée à un natif d'un pays côtier de...   
1852                                         Où es-tu ?   
3328          C'est le cheval que monte l'ange Gabriel.   
5176     Si tu ne tiens pas bien ton sac, on l'arrache.   
1388                  Je te parle à toi fils de Massar.   
9296                           Il dit d'enlever le fil.   
630   À la fin de sa vie, je me souviens qu'il m'a d...   
9782              Attends d'avoir mouillé le couscous !   
776   Ou bien, au moment où je m'y attends le moins,...   
8235       Il y a deux Moringa oleifera dans la maison.   
9268  Un vrai musulman ne jouit pas de biens provena...   
9345  Il éprouve de la gêne à dire ce qu'il a fait d...   
7454  C'est avec la peau de varan de terre qu'on fai...   
3113                 Il dit qu'on a libéré les invités.   
7842           La pipe que tu lui as offerte est belle.   
8849                          As-tu ourlé le pantalon ?   
5413  Si cela te tenait à coeur, tu ne l'aurais pas ...   
6491  Il ne faut pas m'en vouloir pour mon irascibil...   
3516  C'est pour la qualité du travail qu'on a chois...   
370   Face à ces ennemis, la trousse de médecin de m...   
7538  Tu ne sais pas si on a respecté le rite islami...   
780   Je me souviens de chacun d'eux, de leurs noms,...   
6865                       Le fleuve encercle la ville.   
9012                       Je suis un Sérère bon teint.   
4236             Àgg nous arriverons très tôt le matin.   
6749  Il s'est courbé, tu l'as frappé dans le dos av...   
6234              Ne marche pas sur mes plates-bandes !   
4130  De deux choses l'une : ou la chèvre est avec l...   
2816  Nous n'avions pas d'images, nous devions donc ...   
2312         L'homme a tenu aux enfants de bons propos.   
3652     Fais-toi aider par les enfants pour désherber.   
2219                                            Il part   
6119               Seigneur ! pardonne-moi mes péchés !   
6118  Quand les Maures étaient repartis après avoir ...   
2762  Cette photo ci c'est une photo sur laquelle je...   
8870                        Que chacun prenne sa part !   
8204                              Masse-lui la croupe !   
2078                         Tu parles de qui d'autre ?   
756             C'est un cimetière vaste comme un pays.   
9663                             Cela suffit largement.   
8777  Vraiment, je ne saurais te dire la façon qui s...   
2159                Quels moutons qui t'appartiennent ?   
779   L'après-midi, après la leçon de calcul avec ma...   
5460  C'est à moi qu'il lance des flèches, mais je n...   
7898      Ils s'emparent progressivement de notre pays.   
7614  La fourmi que tu as tuée est une créature de D...   
7855                              J'en ai ramassé deux.   
1224                              L'homme n'a pas voulu   
90    Le souvenir que je garde de ce temps pourrait ...   
5061                         Ta sauce est trop épaisse.   
7906                 Arrête de chouchouter cet enfant !   
2903   Viens que je te dise quelque chose à l'oreille !   
1175                                Que l'homme parte ?   
923                           Tu connais cet homme-là ?   
8407           Le vent a fait tomber beaucoup d'arbres.   
5935  Je vends pour un autre, je ne peux pas faire c...   
9826               Tu n'achèterais pas de lait caillé ?   
2083                     Est-ce l'homme qui est parti ?   
6157  Je te parle de billet pour La Mecque, tu fais ...   
241   Dans la salle à manger, nous nous dépêchions d...   
7176  Ce n'était pas la peine de faire une bouchée d...   
4239    C'est par ta négligence que l'enfant est tombé.   
3927        Brûle l'herbe arrachée au

In [152]:
ad5_sentences.sample(74)

french  \
10160  Quand il y a malentendu, c'est qu'il n'y a pas...   
8082               Le petit van est plus facile à tenir.   
11260       Je cherche du Ceratotheca s. pour le bétail.   
6901       Ils se sont entendus pour ne plus lui parler.   
9906                                Il dresse le cheval.   
9285   C'est la photo d'un bébé potelé qu'on a collée...   
8999                                  S'il plaît à Dieu.   
11010  Maintenant c'est différent du temps où tu alla...   
3072              Il essayait de le projeter devant lui.   
4112     C'est cette crème que j'applique sur ma mycose.   
5473                                         C'est inné.   
8095   Les poissons étaient nombreux aujourd'hui au b...   
9719                        Il a encore fait une bêtise.   
1486            Le désir non exaucé de vous voir partir.   
9350                      Ils se sont empoignés soudain.   
616                                         Qui est-ce ?   
8213   Jésus s'est rabaissé au point de laver les pie...   
8734   Ceux qui ont eu leur part, qu'ils aillent atte...   
11440          Certains des étrangers viennent de Dakar.   
3324                              J'ai avalé de travers.   
1227   Cet homme près de moi et celui là près de toi ...   
4108            Les manches de la chemise sont inégales.   
864                  Avoir pu aller jusqu'à Saint-Louis.   
3764                                  Il est un peu fou.   
8207       Donne-moi du papier à rouler les cigarettes !   
7954   La porte est béante et malgré cela il fait chaud.   
7148   Ceux-ci ne font que travailler ici pendant la ...   
5928                   C'est combien le kilo de gombos ?   
10191                                 Déposer les armes.   
7399                                   Où est la sauce ?   
17                               Tu sais, cet homme là ?   
7988                         Que chacun prenne sa part !   
5945                     C'est aujourd'hui qu'Omar part.   
3550   Un francolin ne peut en semer un autre dans un...   
3583     Pour quelle raison as-tu rectifié ta position ?   
832                       Confie la chose à l'un d'eux !   
9266           Ne dis pas son nom, ne parle pas de lui !   
8824                Il est filiforme mais il lutte bien.   
1240                        Tu reconnais cet enfant-ci ?   
4299   Quand il aura besoin de moi, il viendra me tro...   
6548              J'éprouve une grande joie de ta venue.   
2637       C'est la commémoration de notre indépendance.   
1537                              Tu ne vas nulle part !   
4437   Ce n'est pas la peine de creuser, il faut l'ar...   
3647   J'ai habité chez lui pendant un mois et il ne ...   
1969   Rien qu'à l'expression de son visage quand il ...   
7631                     Ces deux villes se ressemblent.   
8348                Sa maison est tout contre la mienne.   
4870   Il est allé implanter sa case au milieu de la ...   
3954                               J'en ai assez de toi.   
6559   Dagana, quand vient la crue, l'eau du fleuve d...   
8221             Ce sont les caresses qui l'ont endormi.   
10712                              Déverses-y du sable !   
8336   Rien n'en est la cause, si ce n'est l'impolite...   
7861                                Certains sont assis.   
1671                                            Arrête !   
2477             Nous devons mettre en commun nos biens.   
2872            Ton feu est bien pris ; viens commencer.   
7131   Celui-là qui se déplace difficilement peut nou...   
2619       Si tu veux le voir, va au bar de la Corniche.   
2122   Certains disaient qu'il ne pourrait pas le fai...   
5767                        Qu'as-tu à t'activer ainsi ?   
4042                                  Je me fais masser.   
6931                 Si tu le mets au soleil, ça fondra.   
1635                                          Bon voyage   
1854   Ceci est une forêt habitée. Il y a beaucoup d'...   
6607   De nombreux fruits nais

In [153]:
corpora_v10.sample(74)

french  \
4322   Quand il est en colère, tout ce qui lui tombe ...   
7920   Quand tu es dans le bus, on te comprime jusqu'...   
10003  Quand dix personnes creusent, dix autres enter...   
8254                         Il a le mal des transports.   
2951                     On garde ses biens près de soi.   
1570                   Eh bien, est-ce qu'il est parti ?   
11105  Décroche la chemise, mets-la avec le linge à l...   
5973                                  Il s'est renversé.   
7472     C'est à cause de l'immoralité qu'il y a en lui.   
6137              Mauvais mari vaut mieux que bon amant.   
2181                  C'est d'autres gens que j'ai vus !   
9137   Le chien a été effrayé, et dans sa course, il ...   
296    Nous avons fait, dans les années qui ont précé...   
11890  Si tu engraisses ton bélier, c'est toi le prem...   
4539                     J'habite du côté est du marché.   
5557       Voilà ta maman qui arrive, va à sa rencontre.   
3031   Quand la gazelle saute par-dessus, son petit n...   
3206                               Commencer à pleuvoir.   
7296              Les animaux qui habitent avec l'homme.   
6056   C'est sur un van qu'on dépose l'aide financièr...   
9549                  Cherche un vacher pour tes vaches.   
7931                                Enlève-lui le mors !   
3285                              J'ai prêté ma voiture.   
7064              Tout ce que tu y as vu lui appartient.   
10826   La grenouille adore l'eau mais pas l'eau chaude.   
1612                           C'est vraiment un homme !   
9557   Quand la période des grosses averses sera pass...   
2928   Celui dont l'ancêtre a été tué par un grand ca...   
2097                                 De quelle manière ?   
4255                                 J'ai des ganglions.   
5347                                        Où va-t-il ?   
35     Mon père a arrêté son auto, avec ma mère il do...   
7413                        La barbe, que tu es rasoir !   
8080   Il dit qu'il n'ouvrira pas le bol tant qu'un g...   
11488                     Deux coudées feront l'affaire.   
5716    Apporte le coutelas à Omar pour qu'il l'affûte !   
12052                           Coupe le jusqu'au coeur.   
4789        C'est son fils qui lui a envoyé de l'argent.   
9961            Qui a remis cette affaire sur le tapis ?   
5224   Je ne peux pas rester assis longtemps en taill...   
9320   Si tu veux être dans une position avantageuse,...   
9509     Va chez ton grand-père prendre un bain lustral.   
852                          Confident lunaire en veille   
6285                                 Qui t'a circoncis ?   
12287              Tu me jalouses à cause de mon couple.   
9809            C'est la mangouste qui a tué le serpent.   
3244   Il ne suffit pas de vouloir partir, il faut po...   
11314  C'est ici que tu fais le fanfaron ; quand tu v...   
3935   Celui qui se réveille avant le maître de maiso...   
2745   Sur cette photo ci, il y a des pierres qui son...   
7744               Tu le trempes dans de l'eau qui bout.   
4435                              L'arbre est bien mort.   
8412   Le vent qui a fait entrer la feuille dans un t...   
346    À l'embouchure du rio Demerara, les palans cha...   
7797                                         J'ai mangé.   
4275               Omar a remporté la victoire sur Omar.   
9306   Il a bourré ses poches de papiers ; je me dema...   
5851                      C'est à mes risques et périls.   
6648   C'est lorsque le lotissement sera terminé qu'o...   
11796  Il lui a tué un taureau châtré quand il est al...   
12209              Il n'a qu'un défaut, de trop pleurer.   
9124                     Le manguier n'a plus de fruits.   
7426                    J'enfant fait rouler un cerceau.   
11772                  Le sermon a été long aujourd'hui.   
7327                          Qu'est-ce qui t'a blessé ?   
1632                    Cet homme n'est qu'intelligence.   
885                   Il n'a p

Let us save the results.

In [154]:
# save the results
ad5_sentences.to_csv('data/extractions/new_data/ad5_sentences.csv', index=False)
corpora_v10.to_csv('data/extractions/new_data/corpora_v10.csv', index=False)
# add_sentences.to_csv('data/extractions/new_data/addd_sentences.csv', index=False)
# corpora_v8.to_csv('data/extractions/new_data/corpora_v8.csv', index=False)
# add_sentences.to_csv('data/extractions/new_data/add_sentences.csv', index=False)
# corpora_v7.to_csv('data/extractions/new_data/corpora_v7.csv', index=False)
# ad_sentences.to_csv('data/extractions/new_data/ad_sentences.csv', index=False)
# corpora_v6.to_csv('data/extractions/new_data/corpora_v6.csv', index=False)
# diagne_sentences.to_csv('data/extractions/new_data/diagne_sentences.csv', index=False)
# corpora_v4.to_csv('data/extractions/new_data/corpora_v4.csv', index=False)

Let us verify how many sentences we got for the moment.

In [155]:
# from diagne's book without scraped sentences
ad_sentences.shape[0]

1977

In [156]:
# inside the corpora without scraped sentences
corpora_v6.shape[0]

2859

In [157]:
# from diagne's book with scraped sentences
add_sentences.shape[0]

4964

In [158]:
# inside the corpora with scraped sentences
corpora_v7.shape[0]

5846

In [159]:
# from diagne's book with scraped sentences
addd_sentences.shape[0]

6963

In [160]:
# inside the corpora with scraped sentences
corpora_v8.shape[0]

7845

In [161]:
# from diagne's book with scraped sentences
ad4_sentences.shape[0]

8961

In [162]:
# inside the corpora with scraped sentences
corpora_v9.shape[0]

9843

In [163]:
# from diagne's book with scraped sentences
ad5_sentences.shape[0]

11426

In [164]:
# inside the corpora with scraped sentences
corpora_v10.shape[0]

12308

We recuperated `11426` sentences from the diagne's book and the final corpora contains `12308` sentences.